// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: P2

#include "../ui.h"

void ui_Home_screen_init(void)
{
    ui_Home = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Home, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Home, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Home, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeHeader = lv_label_create(ui_Home);
    lv_obj_set_width(ui_HomeHeader, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeHeader, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeHeader, -320);
    lv_obj_set_y(ui_HomeHeader, -210);
    lv_obj_set_align(ui_HomeHeader, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HomeHeader, "Home");
    lv_obj_set_style_text_color(ui_HomeHeader, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HomeHeader, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HomeHeader, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeTopLine = lv_obj_create(ui_Home);
    lv_obj_remove_style_all(ui_HomeTopLine);
    lv_obj_set_width(ui_HomeTopLine, 750);
    lv_obj_set_height(ui_HomeTopLine, 2);
    lv_obj_set_x(ui_HomeTopLine, 0);
    lv_obj_set_y(ui_HomeTopLine, -180);
    lv_obj_set_align(ui_HomeTopLine, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_HomeTopLine, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_HomeTopLine, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_HomeTopLine, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_HomeTopLine, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_HomeTopLine, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeBotLine = lv_obj_create(ui_Home);
    lv_obj_remove_style_all(ui_HomeBotLine);
    lv_obj_set_width(ui_HomeBotLine, 750);
    lv_obj_set_height(ui_HomeBotLine, 2);
    lv_obj_set_x(ui_HomeBotLine, 0);
    lv_obj_set_y(ui_HomeBotLine, 180);
    lv_obj_set_align(ui_HomeBotLine, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_HomeBotLine, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_HomeBotLine, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_HomeBotLine, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_HomeBotLine, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_HomeBotLine, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeSpeedBox = lv_obj_create(ui_Home);
    lv_obj_remove_style_all(ui_HomeSpeedBox);
    lv_obj_set_width(ui_HomeSpeedBox, 280);
    lv_obj_set_height(ui_HomeSpeedBox, 200);
    lv_obj_set_x(ui_HomeSpeedBox, -220);
    lv_obj_set_y(ui_HomeSpeedBox, -60);
    lv_obj_set_align(ui_HomeSpeedBox, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_HomeSpeedBox, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HomeSpeedBox, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HomeSpeedBox, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_HomeSpeedBox, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_HomeSpeedBox, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_HomeSpeedBox, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_HomeSpeedBox, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeValueRPM = lv_label_create(ui_HomeSpeedBox);
    lv_obj_set_width(ui_HomeValueRPM, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeValueRPM, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_HomeValueRPM, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HomeValueRPM, "100");
    lv_obj_set_style_text_color(ui_HomeValueRPM, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HomeValueRPM, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HomeValueRPM, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeUnitRPM = lv_label_create(ui_HomeSpeedBox);
    lv_obj_set_width(ui_HomeUnitRPM, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeUnitRPM, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeUnitRPM, 0);
    lv_obj_set_y(ui_HomeUnitRPM, 50);
    lv_obj_set_align(ui_HomeUnitRPM, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HomeUnitRPM, "RPM");
    lv_obj_set_style_text_color(ui_HomeUnitRPM, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HomeUnitRPM, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HomeUnitRPM, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeSpeedRPM = lv_label_create(ui_HomeSpeedBox);
    lv_obj_set_width(ui_HomeSpeedRPM, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeSpeedRPM, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeSpeedRPM, 0);
    lv_obj_set_y(ui_HomeSpeedRPM, -60);
    lv_obj_set_align(ui_HomeSpeedRPM, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HomeSpeedRPM, "Speed");
    lv_obj_set_style_text_color(ui_HomeSpeedRPM, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HomeSpeedRPM, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HomeSpeedRPM, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeFuelRateBox = lv_obj_create(ui_Home);
    lv_obj_remove_style_all(ui_HomeFuelRateBox);
    lv_obj_set_width(ui_HomeFuelRateBox, 135);
    lv_obj_set_height(ui_HomeFuelRateBox, 100);
    lv_obj_set_x(ui_HomeFuelRateBox, -295);
    lv_obj_set_y(ui_HomeFuelRateBox, 110);
    lv_obj_set_align(ui_HomeFuelRateBox, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_HomeFuelRateBox, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HomeFuelRateBox, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HomeFuelRateBox, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_HomeFuelRateBox, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_HomeFuelRateBox, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_HomeFuelRateBox, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_HomeFuelRateBox, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeValueFuelRate = lv_label_create(ui_HomeFuelRateBox);
    lv_obj_set_width(ui_HomeValueFuelRate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeValueFuelRate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeValueFuelRate, 0);
    lv_obj_set_y(ui_HomeValueFuelRate, -25);
    lv_obj_set_align(ui_HomeValueFuelRate, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HomeValueFuelRate, "100");
    lv_obj_set_style_text_color(ui_HomeValueFuelRate, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HomeValueFuelRate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HomeValueFuelRate, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeUnitFuelRate = lv_label_create(ui_HomeFuelRateBox);
    lv_obj_set_width(ui_HomeUnitFuelRate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeUnitFuelRate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeUnitFuelRate, 0);
    lv_obj_set_y(ui_HomeUnitFuelRate, 6);
    lv_obj_set_align(ui_HomeUnitFuelRate, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HomeUnitFuelRate, "L/h");
    lv_obj_set_style_text_color(ui_HomeUnitFuelRate, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HomeUnitFuelRate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HomeUnitFuelRate, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeFuelRate = lv_label_create(ui_HomeFuelRateBox);
    lv_obj_set_width(ui_HomeFuelRate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeFuelRate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeFuelRate, 0);
    lv_obj_set_y(ui_HomeFuelRate, 30);
    lv_obj_set_align(ui_HomeFuelRate, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HomeFuelRate, "Fuel Rate");
    lv_obj_set_style_text_color(ui_HomeFuelRate, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HomeFuelRate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HomeFuelRate, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeLoadBox = lv_obj_create(ui_Home);
    lv_obj_remove_style_all(ui_HomeLoadBox);
    lv_obj_set_width(ui_HomeLoadBox, 135);
    lv_obj_set_height(ui_HomeLoadBox, 100);
    lv_obj_set_x(ui_HomeLoadBox, -145);
    lv_obj_set_y(ui_HomeLoadBox, 110);
    lv_obj_set_align(ui_HomeLoadBox, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_HomeLoadBox, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HomeLoadBox, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HomeLoadBox, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_HomeLoadBox, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_HomeLoadBox, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_HomeLoadBox, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_HomeLoadBox, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeValueLoad = lv_label_create(ui_HomeLoadBox);
    lv_obj_set_width(ui_HomeValueLoad, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeValueLoad, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeValueLoad, 0);
    lv_obj_set_y(ui_HomeValueLoad, -25);
    lv_obj_set_align(ui_HomeValueLoad, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HomeValueLoad, "100");
    lv_obj_set_style_text_color(ui_HomeValueLoad, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HomeValueLoad, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HomeValueLoad, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeUnitLoad = lv_label_create(ui_HomeLoadBox);
    lv_obj_set_width(ui_HomeUnitLoad, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeUnitLoad, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeUnitLoad, 0);
    lv_obj_set_y(ui_HomeUnitLoad, 6);
    lv_obj_set_align(ui_HomeUnitLoad, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HomeUnitLoad, "%");
    lv_obj_set_style_text_color(ui_HomeUnitLoad, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HomeUnitLoad, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HomeUnitLoad, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeLoad = lv_label_create(ui_HomeLoadBox);
    lv_obj_set_width(ui_HomeLoad, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeLoad, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeLoad, 0);
    lv_obj_set_y(ui_HomeLoad, 30);
    lv_obj_set_align(ui_HomeLoad, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HomeLoad, "Load");
    lv_obj_set_style_text_color(ui_HomeLoad, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HomeLoad, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HomeLoad, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeOilPresBox = lv_obj_create(ui_Home);
    lv_obj_remove_style_all(ui_HomeOilPresBox);
    lv_obj_set_width(ui_HomeOilPresBox, 135);
    lv_obj_set_height(ui_HomeOilPresBox, 90);
    lv_obj_set_x(ui_HomeOilPresBox, 0);
    lv_obj_set_y(ui_HomeOilPresBox, -115);
    lv_obj_set_align(ui_HomeOilPresBox, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_HomeOilPresBox, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_HomeOilPresBox, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_HomeOilPresBox, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_HomeOilPresBox, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_HomeOilPresBox, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeValueOilPress = lv_label_create(ui_HomeOilPresBox);
    lv_obj_set_width(ui_HomeValueOilPress, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeValueOilPress, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeValueOilPress, 0);
    lv_obj_set_y(ui_HomeValueOilPress, -20);
    lv_obj_set_align(ui_HomeValueOilPress, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HomeValueOilPress, "100.0");
    lv_obj_set_style_text_color(ui_HomeValueOilPress, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HomeValueOilPress, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HomeValueOilPress, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeUnitOilPress = lv_label_create(ui_HomeOilPresBox);
    lv_obj_set_width(ui_HomeUnitOilPress, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeUnitOilPress, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeUnitOilPress, 0);
    lv_obj_set_y(ui_HomeUnitOilPress, 8);
    lv_obj_set_align(ui_HomeUnitOilPress, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HomeUnitOilPress, "Bar");
    lv_obj_set_style_text_color(ui_HomeUnitOilPress, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HomeUnitOilPress, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HomeUnitOilPress, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeOilPress = lv_label_create(ui_HomeOilPresBox);
    lv_obj_set_width(ui_HomeOilPress, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeOilPress, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeOilPress, 0);
    lv_obj_set_y(ui_HomeOilPress, 30);
    lv_obj_set_align(ui_HomeOilPress, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HomeOilPress, "Oil Press");
    lv_obj_set_style_text_color(ui_HomeOilPress, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HomeOilPress, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HomeOilPress, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeOilTempBox = lv_obj_create(ui_Home);
    lv_obj_remove_style_all(ui_HomeOilTempBox);
    lv_obj_set_width(ui_HomeOilTempBox, 135);
    lv_obj_set_height(ui_HomeOilTempBox, 90);
    lv_obj_set_x(ui_HomeOilTempBox, 150);
    lv_obj_set_y(ui_HomeOilTempBox, -115);
    lv_obj_set_align(ui_HomeOilTempBox, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_HomeOilTempBox, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_HomeOilTempBox, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_HomeOilTempBox, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_HomeOilTempBox, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_HomeOilTempBox, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeValueOilTemp = lv_label_create(ui_HomeOilTempBox);
    lv_obj_set_width(ui_HomeValueOilTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeValueOilTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeValueOilTemp, 0);
    lv_obj_set_y(ui_HomeValueOilTemp, -20);
    lv_obj_set_align(ui_HomeValueOilTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HomeValueOilTemp, "100.0");
    lv_obj_set_style_text_color(ui_HomeValueOilTemp, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HomeValueOilTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HomeValueOilTemp, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeUnitOilTemp = lv_label_create(ui_HomeOilTempBox);
    lv_obj_set_width(ui_HomeUnitOilTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeUnitOilTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeUnitOilTemp, 0);
    lv_obj_set_y(ui_HomeUnitOilTemp, 8);
    lv_obj_set_align(ui_HomeUnitOilTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HomeUnitOilTemp, "°C");
    lv_obj_set_style_text_color(ui_HomeUnitOilTemp, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HomeUnitOilTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HomeUnitOilTemp, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeOilTemp = lv_label_create(ui_HomeOilTempBox);
    lv_obj_set_width(ui_HomeOilTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeOilTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeOilTemp, 0);
    lv_obj_set_y(ui_HomeOilTemp, 30);
    lv_obj_set_align(ui_HomeOilTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HomeOilTemp, "Oil Temp");
    lv_obj_set_style_text_color(ui_HomeOilTemp, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HomeOilTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HomeOilTemp, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeCoolTempBox = lv_obj_create(ui_Home);
    lv_obj_remove_style_all(ui_HomeCoolTempBox);
    lv_obj_set_width(ui_HomeCoolTempBox, 135);
    lv_obj_set_height(ui_HomeCoolTempBox, 90);
    lv_obj_set_x(ui_HomeCoolTempBox, 300);
    lv_obj_set_y(ui_HomeCoolTempBox, -115);
    lv_obj_set_align(ui_HomeCoolTempBox, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_HomeCoolTempBox, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_HomeCoolTempBox, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_HomeCoolTempBox, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_HomeCoolTempBox, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_HomeCoolTempBox, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeValueCoolTemp = lv_label_create(ui_HomeCoolTempBox);
    lv_obj_set_width(ui_HomeValueCoolTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeValueCoolTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeValueCoolTemp, 0);
    lv_obj_set_y(ui_HomeValueCoolTemp, -20);
    lv_obj_set_align(ui_HomeValueCoolTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HomeValueCoolTemp, "100.0");
    lv_obj_set_style_text_color(ui_HomeValueCoolTemp, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HomeValueCoolTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HomeValueCoolTemp, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeUnitCoolTemp = lv_label_create(ui_HomeCoolTempBox);
    lv_obj_set_width(ui_HomeUnitCoolTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeUnitCoolTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeUnitCoolTemp, 0);
    lv_obj_set_y(ui_HomeUnitCoolTemp, 8);
    lv_obj_set_align(ui_HomeUnitCoolTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HomeUnitCoolTemp, "°C");
    lv_obj_set_style_text_color(ui_HomeUnitCoolTemp, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HomeUnitCoolTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HomeUnitCoolTemp, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeCoolTemp = lv_label_create(ui_HomeCoolTempBox);
    lv_obj_set_width(ui_HomeCoolTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeCoolTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeCoolTemp, 0);
    lv_obj_set_y(ui_HomeCoolTemp, 30);
    lv_obj_set_align(ui_HomeCoolTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HomeCoolTemp, "Cool Temp");
    lv_obj_set_style_text_color(ui_HomeCoolTemp, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HomeCoolTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HomeCoolTemp, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeIntakePressBox = lv_obj_create(ui_Home);
    lv_obj_remove_style_all(ui_HomeIntakePressBox);
    lv_obj_set_width(ui_HomeIntakePressBox, 135);
    lv_obj_set_height(ui_HomeIntakePressBox, 90);
    lv_obj_set_align(ui_HomeIntakePressBox, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_HomeIntakePressBox, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_HomeIntakePressBox, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_HomeIntakePressBox, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_HomeIntakePressBox, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_HomeIntakePressBox, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeValueIntakePress = lv_label_create(ui_HomeIntakePressBox);
    lv_obj_set_width(ui_HomeValueIntakePress, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeValueIntakePress, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeValueIntakePress, 0);
    lv_obj_set_y(ui_HomeValueIntakePress, -20);
    lv_obj_set_align(ui_HomeValueIntakePress, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HomeValueIntakePress, "100.0");
    lv_obj_set_style_text_color(ui_HomeValueIntakePress, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HomeValueIntakePress, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HomeValueIntakePress, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeUnitIntakePress = lv_label_create(ui_HomeIntakePressBox);
    lv_obj_set_width(ui_HomeUnitIntakePress, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeUnitIntakePress, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeUnitIntakePress, 0);
    lv_obj_set_y(ui_HomeUnitIntakePress, 8);
    lv_obj_set_align(ui_HomeUnitIntakePress, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HomeUnitIntakePress, "Bar");
    lv_obj_set_style_text_color(ui_HomeUnitIntakePress, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HomeUnitIntakePress, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HomeUnitIntakePress, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeIntakePress = lv_label_create(ui_HomeIntakePressBox);
    lv_obj_set_width(ui_HomeIntakePress, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeIntakePress, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeIntakePress, 0);
    lv_obj_set_y(ui_HomeIntakePress, 30);
    lv_obj_set_align(ui_HomeIntakePress, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HomeIntakePress, "Intake Press");
    lv_obj_set_style_text_color(ui_HomeIntakePress, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HomeIntakePress, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HomeIntakePress, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeIntakeTempBox = lv_obj_create(ui_Home);
    lv_obj_remove_style_all(ui_HomeIntakeTempBox);
    lv_obj_set_width(ui_HomeIntakeTempBox, 135);
    lv_obj_set_height(ui_HomeIntakeTempBox, 90);
    lv_obj_set_x(ui_HomeIntakeTempBox, 150);
    lv_obj_set_y(ui_HomeIntakeTempBox, 0);
    lv_obj_set_align(ui_HomeIntakeTempBox, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_HomeIntakeTempBox, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_HomeIntakeTempBox, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_HomeIntakeTempBox, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_HomeIntakeTempBox, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_HomeIntakeTempBox, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeValueIntakeTemp = lv_label_create(ui_HomeIntakeTempBox);
    lv_obj_set_width(ui_HomeValueIntakeTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeValueIntakeTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeValueIntakeTemp, 0);
    lv_obj_set_y(ui_HomeValueIntakeTemp, -20);
    lv_obj_set_align(ui_HomeValueIntakeTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HomeValueIntakeTemp, "100.0");
    lv_obj_set_style_text_color(ui_HomeValueIntakeTemp, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HomeValueIntakeTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HomeValueIntakeTemp, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeUnitIntakeTemp = lv_label_create(ui_HomeIntakeTempBox);
    lv_obj_set_width(ui_HomeUnitIntakeTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeUnitIntakeTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeUnitIntakeTemp, 0);
    lv_obj_set_y(ui_HomeUnitIntakeTemp, 8);
    lv_obj_set_align(ui_HomeUnitIntakeTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HomeUnitIntakeTemp, "°C");
    lv_obj_set_style_text_color(ui_HomeUnitIntakeTemp, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HomeUnitIntakeTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HomeUnitIntakeTemp, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeIntakeTemp = lv_label_create(ui_HomeIntakeTempBox);
    lv_obj_set_width(ui_HomeIntakeTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeIntakeTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeIntakeTemp, 0);
    lv_obj_set_y(ui_HomeIntakeTemp, 30);
    lv_obj_set_align(ui_HomeIntakeTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HomeIntakeTemp, "Intake Temp");
    lv_obj_set_style_text_color(ui_HomeIntakeTemp, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HomeIntakeTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HomeIntakeTemp, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeExhaustTempBox = lv_obj_create(ui_Home);
    lv_obj_remove_style_all(ui_HomeExhaustTempBox);
    lv_obj_set_width(ui_HomeExhaustTempBox, 135);
    lv_obj_set_height(ui_HomeExhaustTempBox, 90);
    lv_obj_set_x(ui_HomeExhaustTempBox, 300);
    lv_obj_set_y(ui_HomeExhaustTempBox, 0);
    lv_obj_set_align(ui_HomeExhaustTempBox, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_HomeExhaustTempBox, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_HomeExhaustTempBox, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_HomeExhaustTempBox, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_HomeExhaustTempBox, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_HomeExhaustTempBox, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeValueExhaustTemp = lv_label_create(ui_HomeExhaustTempBox);
    lv_obj_set_width(ui_HomeValueExhaustTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeValueExhaustTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeValueExhaustTemp, 0);
    lv_obj_set_y(ui_HomeValueExhaustTemp, -20);
    lv_obj_set_align(ui_HomeValueExhaustTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HomeValueExhaustTemp, "100.0");
    lv_obj_set_style_text_color(ui_HomeValueExhaustTemp, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HomeValueExhaustTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HomeValueExhaustTemp, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeUnitExhaustTemp = lv_label_create(ui_HomeExhaustTempBox);
    lv_obj_set_width(ui_HomeUnitExhaustTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeUnitExhaustTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeUnitExhaustTemp, 0);
    lv_obj_set_y(ui_HomeUnitExhaustTemp, 8);
    lv_obj_set_align(ui_HomeUnitExhaustTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HomeUnitExhaustTemp, "°C");
    lv_obj_set_style_text_color(ui_HomeUnitExhaustTemp, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HomeUnitExhaustTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HomeUnitExhaustTemp, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeExhaustTemp = lv_label_create(ui_HomeExhaustTempBox);
    lv_obj_set_width(ui_HomeExhaustTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeExhaustTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeExhaustTemp, 0);
    lv_obj_set_y(ui_HomeExhaustTemp, 30);
    lv_obj_set_align(ui_HomeExhaustTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HomeExhaustTemp, "Exhaust Temp");
    lv_obj_set_style_text_color(ui_HomeExhaustTemp, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HomeExhaustTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HomeExhaustTemp, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeStatusBox = lv_obj_create(ui_Home);
    lv_obj_remove_style_all(ui_HomeStatusBox);
    lv_obj_set_width(ui_HomeStatusBox, 135);
    lv_obj_set_height(ui_HomeStatusBox, 90);
    lv_obj_set_x(ui_HomeStatusBox, 0);
    lv_obj_set_y(ui_HomeStatusBox, 115);
    lv_obj_set_align(ui_HomeStatusBox, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_HomeStatusBox, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_HomeStatusBox, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_HomeStatusBox, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_HomeStatusBox, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_HomeStatusBox, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeStatus = lv_label_create(ui_HomeStatusBox);
    lv_obj_set_width(ui_HomeStatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_HomeStatus, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HomeStatus, "Command");
    lv_obj_set_style_text_color(ui_HomeStatus, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HomeStatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HomeStatus, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeECUStatusBox = lv_obj_create(ui_Home);
    lv_obj_remove_style_all(ui_HomeECUStatusBox);
    lv_obj_set_width(ui_HomeECUStatusBox, 135);
    lv_obj_set_height(ui_HomeECUStatusBox, 90);
    lv_obj_set_x(ui_HomeECUStatusBox, 150);
    lv_obj_set_y(ui_HomeECUStatusBox, 115);
    lv_obj_set_align(ui_HomeECUStatusBox, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_HomeECUStatusBox, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_HomeECUStatusBox, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_HomeECUStatusBox, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_HomeECUStatusBox, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_HomeECUStatusBox, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeEcuStatus = lv_label_create(ui_HomeECUStatusBox);
    lv_obj_set_width(ui_HomeEcuStatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeEcuStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeEcuStatus, -27);
    lv_obj_set_y(ui_HomeEcuStatus, -35);
    lv_obj_set_align(ui_HomeEcuStatus, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HomeEcuStatus, "Ecu On / Off");
    lv_obj_set_style_text_color(ui_HomeEcuStatus, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HomeEcuStatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HomeEcuStatus, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomePWRLimit = lv_label_create(ui_HomeECUStatusBox);
    lv_obj_set_width(ui_HomePWRLimit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomePWRLimit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomePWRLimit, -31);
    lv_obj_set_y(ui_HomePWRLimit, -20);
    lv_obj_set_align(ui_HomePWRLimit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HomePWRLimit, "PWR Limit");
    lv_obj_set_style_text_color(ui_HomePWRLimit, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HomePWRLimit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HomePWRLimit, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeBatteryVolt = lv_label_create(ui_HomeECUStatusBox);
    lv_obj_set_width(ui_HomeBatteryVolt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeBatteryVolt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeBatteryVolt, -27);
    lv_obj_set_y(ui_HomeBatteryVolt, -6);
    lv_obj_set_align(ui_HomeBatteryVolt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HomeBatteryVolt, "Battery Volt");
    lv_obj_set_style_text_color(ui_HomeBatteryVolt, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HomeBatteryVolt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HomeBatteryVolt, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeServiceTime = lv_label_create(ui_HomeECUStatusBox);
    lv_obj_set_width(ui_HomeServiceTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeServiceTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeServiceTime, -25);
    lv_obj_set_y(ui_HomeServiceTime, 8);
    lv_obj_set_align(ui_HomeServiceTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HomeServiceTime, "Service Time");
    lv_obj_set_style_text_color(ui_HomeServiceTime, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HomeServiceTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HomeServiceTime, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeRunHours = lv_label_create(ui_HomeECUStatusBox);
    lv_obj_set_width(ui_HomeRunHours, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeRunHours, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeRunHours, -31);
    lv_obj_set_y(ui_HomeRunHours, 21);
    lv_obj_set_align(ui_HomeRunHours, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HomeRunHours, "Run Hours");
    lv_obj_set_style_text_color(ui_HomeRunHours, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HomeRunHours, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HomeRunHours, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeDayCons = lv_label_create(ui_HomeECUStatusBox);
    lv_obj_set_width(ui_HomeDayCons, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeDayCons, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeDayCons, -35);
    lv_obj_set_y(ui_HomeDayCons, 34);
    lv_obj_set_align(ui_HomeDayCons, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HomeDayCons, "Day Cons");
    lv_obj_set_style_text_color(ui_HomeDayCons, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HomeDayCons, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HomeDayCons, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeValueBatteryVolt = lv_label_create(ui_HomeECUStatusBox);
    lv_obj_set_width(ui_HomeValueBatteryVolt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeValueBatteryVolt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeValueBatteryVolt, 38);
    lv_obj_set_y(ui_HomeValueBatteryVolt, -6);
    lv_obj_set_align(ui_HomeValueBatteryVolt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HomeValueBatteryVolt, "25.0");
    lv_obj_set_style_text_color(ui_HomeValueBatteryVolt, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HomeValueBatteryVolt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HomeValueBatteryVolt, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeValueServiceTime = lv_label_create(ui_HomeECUStatusBox);
    lv_obj_set_width(ui_HomeValueServiceTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeValueServiceTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeValueServiceTime, 37);
    lv_obj_set_y(ui_HomeValueServiceTime, 8);
    lv_obj_set_align(ui_HomeValueServiceTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HomeValueServiceTime, "1000");
    lv_obj_set_style_text_color(ui_HomeValueServiceTime, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HomeValueServiceTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HomeValueServiceTime, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeValueRunHours = lv_label_create(ui_HomeECUStatusBox);
    lv_obj_set_width(ui_HomeValueRunHours, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeValueRunHours, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeValueRunHours, 37);
    lv_obj_set_y(ui_HomeValueRunHours, 21);
    lv_obj_set_align(ui_HomeValueRunHours, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HomeValueRunHours, "1000");
    lv_obj_set_style_text_color(ui_HomeValueRunHours, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HomeValueRunHours, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HomeValueRunHours, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeValueDayCons = lv_label_create(ui_HomeECUStatusBox);
    lv_obj_set_width(ui_HomeValueDayCons, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeValueDayCons, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeValueDayCons, 36);
    lv_obj_set_y(ui_HomeValueDayCons, 34);
    lv_obj_set_align(ui_HomeValueDayCons, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HomeValueDayCons, "1945");
    lv_obj_set_style_text_color(ui_HomeValueDayCons, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HomeValueDayCons, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HomeValueDayCons, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeUnitBatteryVolt = lv_label_create(ui_HomeECUStatusBox);
    lv_obj_set_width(ui_HomeUnitBatteryVolt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeUnitBatteryVolt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeUnitBatteryVolt, 59);
    lv_obj_set_y(ui_HomeUnitBatteryVolt, -6);
    lv_obj_set_align(ui_HomeUnitBatteryVolt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HomeUnitBatteryVolt, "V");
    lv_obj_set_style_text_color(ui_HomeUnitBatteryVolt, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HomeUnitBatteryVolt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HomeUnitBatteryVolt, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeUnitServiceTime = lv_label_create(ui_HomeECUStatusBox);
    lv_obj_set_width(ui_HomeUnitServiceTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeUnitServiceTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeUnitServiceTime, 59);
    lv_obj_set_y(ui_HomeUnitServiceTime, 8);
    lv_obj_set_align(ui_HomeUnitServiceTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HomeUnitServiceTime, "h");
    lv_obj_set_style_text_color(ui_HomeUnitServiceTime, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HomeUnitServiceTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HomeUnitServiceTime, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeUnitRunHours = lv_label_create(ui_HomeECUStatusBox);
    lv_obj_set_width(ui_HomeUnitRunHours, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeUnitRunHours, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeUnitRunHours, 59);
    lv_obj_set_y(ui_HomeUnitRunHours, 21);
    lv_obj_set_align(ui_HomeUnitRunHours, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HomeUnitRunHours, "h");
    lv_obj_set_style_text_color(ui_HomeUnitRunHours, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HomeUnitRunHours, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HomeUnitRunHours, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeRTCBox = lv_obj_create(ui_Home);
    lv_obj_remove_style_all(ui_HomeRTCBox);
    lv_obj_set_width(ui_HomeRTCBox, 135);
    lv_obj_set_height(ui_HomeRTCBox, 90);
    lv_obj_set_x(ui_HomeRTCBox, 300);
    lv_obj_set_y(ui_HomeRTCBox, 115);
    lv_obj_set_align(ui_HomeRTCBox, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_HomeRTCBox, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_HomeRTCBox, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_HomeRTCBox, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_HomeRTCBox, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_HomeRTCBox, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeDeviceType = lv_label_create(ui_HomeRTCBox);
    lv_obj_set_width(ui_HomeDeviceType, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeDeviceType, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeDeviceType, 0);
    lv_obj_set_y(ui_HomeDeviceType, -30);
    lv_obj_set_align(ui_HomeDeviceType, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HomeDeviceType, "2M263-0197");
    lv_obj_set_style_text_color(ui_HomeDeviceType, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HomeDeviceType, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HomeDeviceType, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeTime = lv_label_create(ui_HomeRTCBox);
    lv_obj_set_width(ui_HomeTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeTime, 0);
    lv_obj_set_y(ui_HomeTime, -5);
    lv_obj_set_align(ui_HomeTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HomeTime, "12 : 12");
    lv_obj_set_style_text_color(ui_HomeTime, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HomeTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HomeTime, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeBotLineRTC = lv_obj_create(ui_HomeRTCBox);
    lv_obj_remove_style_all(ui_HomeBotLineRTC);
    lv_obj_set_width(ui_HomeBotLineRTC, 132);
    lv_obj_set_height(ui_HomeBotLineRTC, 2);
    lv_obj_set_x(ui_HomeBotLineRTC, 0);
    lv_obj_set_y(ui_HomeBotLineRTC, 20);
    lv_obj_set_align(ui_HomeBotLineRTC, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_HomeBotLineRTC, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_HomeBotLineRTC, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_HomeBotLineRTC, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_HomeBotLineRTC, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_HomeBotLineRTC, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeDate = lv_label_create(ui_HomeRTCBox);
    lv_obj_set_width(ui_HomeDate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeDate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeDate, 0);
    lv_obj_set_y(ui_HomeDate, 32);
    lv_obj_set_align(ui_HomeDate, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HomeDate, "12/12/2012");
    lv_obj_set_style_text_color(ui_HomeDate, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HomeDate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HomeDate, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Home, ui_event_SlideScreen, LV_EVENT_ALL, NULL);
}
