// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: P2

#include "../ui.h"

void ui_Service_screen_init(void)
{
    ui_Service = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Service, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Service, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Service, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_flag(ui_Service, LV_OBJ_FLAG_CHECKABLE);

    ui_ServiceHeader = lv_label_create(ui_Service);
    lv_obj_set_width(ui_ServiceHeader, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ServiceHeader, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ServiceHeader, -320);
    lv_obj_set_y(ui_ServiceHeader, -210);
    lv_obj_set_align(ui_ServiceHeader, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ServiceHeader, "Service");
    lv_obj_set_style_text_color(ui_ServiceHeader, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ServiceHeader, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ServiceHeader, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ServiceTopLine = lv_obj_create(ui_Service);
    lv_obj_remove_style_all(ui_ServiceTopLine);
    lv_obj_set_width(ui_ServiceTopLine, 750);
    lv_obj_set_height(ui_ServiceTopLine, 2);
    lv_obj_set_x(ui_ServiceTopLine, 0);
    lv_obj_set_y(ui_ServiceTopLine, -180);
    lv_obj_set_align(ui_ServiceTopLine, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ServiceTopLine, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_ServiceTopLine, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ServiceTopLine, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ServiceTopLine, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ServiceTopLine, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ServiceBotLine = lv_obj_create(ui_Service);
    lv_obj_remove_style_all(ui_ServiceBotLine);
    lv_obj_set_width(ui_ServiceBotLine, 750);
    lv_obj_set_height(ui_ServiceBotLine, 2);
    lv_obj_set_x(ui_ServiceBotLine, 0);
    lv_obj_set_y(ui_ServiceBotLine, 180);
    lv_obj_set_align(ui_ServiceBotLine, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ServiceBotLine, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_ServiceBotLine, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ServiceBotLine, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ServiceBotLine, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ServiceBotLine, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ServiceRPMBox = lv_obj_create(ui_Service);
    lv_obj_remove_style_all(ui_ServiceRPMBox);
    lv_obj_set_width(ui_ServiceRPMBox, 180);
    lv_obj_set_height(ui_ServiceRPMBox, 362);
    lv_obj_set_x(ui_ServiceRPMBox, -287);
    lv_obj_set_y(ui_ServiceRPMBox, 0);
    lv_obj_set_align(ui_ServiceRPMBox, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ServiceRPMBox, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_ServiceRPMBox, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ServiceRPMBox, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ServiceRPMBox, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ServiceRPMBox, LV_BORDER_SIDE_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TopLineRPMBox = lv_obj_create(ui_ServiceRPMBox);
    lv_obj_remove_style_all(ui_TopLineRPMBox);
    lv_obj_set_width(ui_TopLineRPMBox, 160);
    lv_obj_set_height(ui_TopLineRPMBox, 2);
    lv_obj_set_x(ui_TopLineRPMBox, 0);
    lv_obj_set_y(ui_TopLineRPMBox, -130);
    lv_obj_set_align(ui_TopLineRPMBox, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TopLineRPMBox, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_TopLineRPMBox, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TopLineRPMBox, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_TopLineRPMBox, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_TopLineRPMBox, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BotLineRPMBox = lv_obj_create(ui_ServiceRPMBox);
    lv_obj_remove_style_all(ui_BotLineRPMBox);
    lv_obj_set_width(ui_BotLineRPMBox, 160);
    lv_obj_set_height(ui_BotLineRPMBox, 2);
    lv_obj_set_x(ui_BotLineRPMBox, 0);
    lv_obj_set_y(ui_BotLineRPMBox, 100);
    lv_obj_set_align(ui_BotLineRPMBox, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BotLineRPMBox, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_BotLineRPMBox, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BotLineRPMBox, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BotLineRPMBox, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_BotLineRPMBox, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ServiceRPM = lv_label_create(ui_ServiceRPMBox);
    lv_obj_set_width(ui_ServiceRPM, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ServiceRPM, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ServiceRPM, 0);
    lv_obj_set_y(ui_ServiceRPM, -155);
    lv_obj_set_align(ui_ServiceRPM, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ServiceRPM, "RPM");
    lv_obj_set_style_text_color(ui_ServiceRPM, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ServiceRPM, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ServiceRPM, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ServiceSpeedToECU = lv_label_create(ui_ServiceRPMBox);
    lv_obj_set_width(ui_ServiceSpeedToECU, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ServiceSpeedToECU, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ServiceSpeedToECU, 0);
    lv_obj_set_y(ui_ServiceSpeedToECU, -115);
    lv_obj_set_align(ui_ServiceSpeedToECU, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ServiceSpeedToECU, "Speed To ECU :");
    lv_obj_set_style_text_color(ui_ServiceSpeedToECU, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ServiceSpeedToECU, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ServiceSpeedToECU, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ServiceValueSpeedToECU = lv_label_create(ui_ServiceRPMBox);
    lv_obj_set_width(ui_ServiceValueSpeedToECU, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ServiceValueSpeedToECU, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ServiceValueSpeedToECU, 0);
    lv_obj_set_y(ui_ServiceValueSpeedToECU, -75);
    lv_obj_set_align(ui_ServiceValueSpeedToECU, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ServiceValueSpeedToECU, "100");
    lv_obj_set_style_text_color(ui_ServiceValueSpeedToECU, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ServiceValueSpeedToECU, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ServiceValueSpeedToECU, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ServiceUnitSpeedToECU = lv_label_create(ui_ServiceRPMBox);
    lv_obj_set_width(ui_ServiceUnitSpeedToECU, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ServiceUnitSpeedToECU, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ServiceUnitSpeedToECU, 0);
    lv_obj_set_y(ui_ServiceUnitSpeedToECU, -35);
    lv_obj_set_align(ui_ServiceUnitSpeedToECU, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ServiceUnitSpeedToECU, "RPM");
    lv_obj_set_style_text_color(ui_ServiceUnitSpeedToECU, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ServiceUnitSpeedToECU, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ServiceUnitSpeedToECU, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ServiceSpeedRequest = lv_label_create(ui_ServiceRPMBox);
    lv_obj_set_width(ui_ServiceSpeedRequest, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ServiceSpeedRequest, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ServiceSpeedRequest, 0);
    lv_obj_set_y(ui_ServiceSpeedRequest, 5);
    lv_obj_set_align(ui_ServiceSpeedRequest, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ServiceSpeedRequest, "Speed Request :");
    lv_obj_set_style_text_color(ui_ServiceSpeedRequest, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ServiceSpeedRequest, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ServiceSpeedRequest, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ServiceValueSpeedRequest = lv_label_create(ui_ServiceRPMBox);
    lv_obj_set_width(ui_ServiceValueSpeedRequest, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ServiceValueSpeedRequest, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ServiceValueSpeedRequest, 0);
    lv_obj_set_y(ui_ServiceValueSpeedRequest, 45);
    lv_obj_set_align(ui_ServiceValueSpeedRequest, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ServiceValueSpeedRequest, "100");
    lv_obj_set_style_text_color(ui_ServiceValueSpeedRequest, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ServiceValueSpeedRequest, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ServiceValueSpeedRequest, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ServiceUnitSpeedRequest = lv_label_create(ui_ServiceRPMBox);
    lv_obj_set_width(ui_ServiceUnitSpeedRequest, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ServiceUnitSpeedRequest, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ServiceUnitSpeedRequest, 0);
    lv_obj_set_y(ui_ServiceUnitSpeedRequest, 80);
    lv_obj_set_align(ui_ServiceUnitSpeedRequest, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ServiceUnitSpeedRequest, "RPM");
    lv_obj_set_style_text_color(ui_ServiceUnitSpeedRequest, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ServiceUnitSpeedRequest, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ServiceUnitSpeedRequest, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ServiceLoad = lv_label_create(ui_ServiceRPMBox);
    lv_obj_set_width(ui_ServiceLoad, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ServiceLoad, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ServiceLoad, -55);
    lv_obj_set_y(ui_ServiceLoad, 140);
    lv_obj_set_align(ui_ServiceLoad, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ServiceLoad, "Load :");
    lv_obj_set_style_text_color(ui_ServiceLoad, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ServiceLoad, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ServiceLoad, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ServiceValueLoad = lv_label_create(ui_ServiceRPMBox);
    lv_obj_set_width(ui_ServiceValueLoad, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ServiceValueLoad, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ServiceValueLoad, 10);
    lv_obj_set_y(ui_ServiceValueLoad, 140);
    lv_obj_set_align(ui_ServiceValueLoad, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ServiceValueLoad, "100");
    lv_obj_set_style_text_color(ui_ServiceValueLoad, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ServiceValueLoad, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ServiceValueLoad, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ServiceUnitLoad = lv_label_create(ui_ServiceRPMBox);
    lv_obj_set_width(ui_ServiceUnitLoad, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ServiceUnitLoad, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ServiceUnitLoad, 55);
    lv_obj_set_y(ui_ServiceUnitLoad, 140);
    lv_obj_set_align(ui_ServiceUnitLoad, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ServiceUnitLoad, "%");
    lv_obj_set_style_text_color(ui_ServiceUnitLoad, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ServiceUnitLoad, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ServiceUnitLoad, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ServicePropulsionBox = lv_obj_create(ui_Service);
    lv_obj_remove_style_all(ui_ServicePropulsionBox);
    lv_obj_set_width(ui_ServicePropulsionBox, 200);
    lv_obj_set_height(ui_ServicePropulsionBox, 362);
    lv_obj_set_x(ui_ServicePropulsionBox, -99);
    lv_obj_set_y(ui_ServicePropulsionBox, 0);
    lv_obj_set_align(ui_ServicePropulsionBox, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ServicePropulsionBox, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_ServicePropulsionBox, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ServicePropulsionBox, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ServicePropulsionBox, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ServicePropulsionBox, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BotLinePropulsionBox = lv_obj_create(ui_ServicePropulsionBox);
    lv_obj_remove_style_all(ui_BotLinePropulsionBox);
    lv_obj_set_width(ui_BotLinePropulsionBox, 160);
    lv_obj_set_height(ui_BotLinePropulsionBox, 2);
    lv_obj_set_x(ui_BotLinePropulsionBox, 0);
    lv_obj_set_y(ui_BotLinePropulsionBox, -130);
    lv_obj_set_align(ui_BotLinePropulsionBox, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BotLinePropulsionBox, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_BotLinePropulsionBox, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BotLinePropulsionBox, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BotLinePropulsionBox, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_BotLinePropulsionBox, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ServicePropulsion = lv_label_create(ui_ServicePropulsionBox);
    lv_obj_set_width(ui_ServicePropulsion, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ServicePropulsion, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ServicePropulsion, 0);
    lv_obj_set_y(ui_ServicePropulsion, -155);
    lv_obj_set_align(ui_ServicePropulsion, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ServicePropulsion, "Propulsion");
    lv_obj_set_style_text_color(ui_ServicePropulsion, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ServicePropulsion, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ServicePropulsion, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ServiceLever = lv_label_create(ui_ServicePropulsionBox);
    lv_obj_set_width(ui_ServiceLever, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ServiceLever, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ServiceLever, -55);
    lv_obj_set_y(ui_ServiceLever, -110);
    lv_obj_set_align(ui_ServiceLever, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ServiceLever, "Lever");
    lv_obj_set_style_text_color(ui_ServiceLever, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ServiceLever, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ServiceLever, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ServiceLever, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ServiceLever, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ServiceLever, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ServiceLever, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ServiceForwardPos = lv_label_create(ui_ServicePropulsionBox);
    lv_obj_set_width(ui_ServiceForwardPos, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ServiceForwardPos, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ServiceForwardPos, -45);
    lv_obj_set_y(ui_ServiceForwardPos, -80);
    lv_obj_set_align(ui_ServiceForwardPos, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ServiceForwardPos, "Forward Pos");
    lv_obj_set_style_text_color(ui_ServiceForwardPos, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ServiceForwardPos, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ServiceForwardPos, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ServiceValueForwardPos = lv_label_create(ui_ServicePropulsionBox);
    lv_obj_set_width(ui_ServiceValueForwardPos, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ServiceValueForwardPos, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ServiceValueForwardPos, 50);
    lv_obj_set_y(ui_ServiceValueForwardPos, -80);
    lv_obj_set_align(ui_ServiceValueForwardPos, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ServiceValueForwardPos, "0");
    lv_obj_set_style_text_color(ui_ServiceValueForwardPos, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ServiceValueForwardPos, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ServiceValueForwardPos, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ServiceReversePos = lv_label_create(ui_ServicePropulsionBox);
    lv_obj_set_width(ui_ServiceReversePos, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ServiceReversePos, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ServiceReversePos, -47);
    lv_obj_set_y(ui_ServiceReversePos, -60);
    lv_obj_set_align(ui_ServiceReversePos, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ServiceReversePos, "Reverse Pos");
    lv_obj_set_style_text_color(ui_ServiceReversePos, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ServiceReversePos, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ServiceReversePos, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ServiceValueReversePos = lv_label_create(ui_ServicePropulsionBox);
    lv_obj_set_width(ui_ServiceValueReversePos, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ServiceValueReversePos, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ServiceValueReversePos, 50);
    lv_obj_set_y(ui_ServiceValueReversePos, -60);
    lv_obj_set_align(ui_ServiceValueReversePos, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ServiceValueReversePos, "0");
    lv_obj_set_style_text_color(ui_ServiceValueReversePos, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ServiceValueReversePos, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ServiceValueReversePos, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ServiceStNeutral = lv_label_create(ui_ServicePropulsionBox);
    lv_obj_set_width(ui_ServiceStNeutral, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ServiceStNeutral, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ServiceStNeutral, -56);
    lv_obj_set_y(ui_ServiceStNeutral, -40);
    lv_obj_set_align(ui_ServiceStNeutral, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ServiceStNeutral, "StNeutral");
    lv_obj_set_style_text_color(ui_ServiceStNeutral, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ServiceStNeutral, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ServiceStNeutral, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ServiceValueStNeutral = lv_label_create(ui_ServicePropulsionBox);
    lv_obj_set_width(ui_ServiceValueStNeutral, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ServiceValueStNeutral, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ServiceValueStNeutral, 50);
    lv_obj_set_y(ui_ServiceValueStNeutral, -40);
    lv_obj_set_align(ui_ServiceValueStNeutral, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ServiceValueStNeutral, "0");
    lv_obj_set_style_text_color(ui_ServiceValueStNeutral, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ServiceValueStNeutral, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ServiceValueStNeutral, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ServiceLeverPosition = lv_label_create(ui_ServicePropulsionBox);
    lv_obj_set_width(ui_ServiceLeverPosition, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ServiceLeverPosition, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ServiceLeverPosition, -41);
    lv_obj_set_y(ui_ServiceLeverPosition, -20);
    lv_obj_set_align(ui_ServiceLeverPosition, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ServiceLeverPosition, "LeverPosition");
    lv_obj_set_style_text_color(ui_ServiceLeverPosition, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ServiceLeverPosition, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ServiceLeverPosition, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ServiceValueLeverPosition = lv_label_create(ui_ServicePropulsionBox);
    lv_obj_set_width(ui_ServiceValueLeverPosition, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ServiceValueLeverPosition, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ServiceValueLeverPosition, 50);
    lv_obj_set_y(ui_ServiceValueLeverPosition, -20);
    lv_obj_set_align(ui_ServiceValueLeverPosition, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ServiceValueLeverPosition, "0");
    lv_obj_set_style_text_color(ui_ServiceValueLeverPosition, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ServiceValueLeverPosition, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ServiceValueLeverPosition, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ServiceState = lv_label_create(ui_ServicePropulsionBox);
    lv_obj_set_width(ui_ServiceState, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ServiceState, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ServiceState, -55);
    lv_obj_set_y(ui_ServiceState, 10);
    lv_obj_set_align(ui_ServiceState, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ServiceState, "State");
    lv_obj_set_style_text_color(ui_ServiceState, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ServiceState, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ServiceState, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ServiceState, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ServiceState, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ServiceState, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ServiceState, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ServiceStForwSol = lv_label_create(ui_ServicePropulsionBox);
    lv_obj_set_width(ui_ServiceStForwSol, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ServiceStForwSol, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ServiceStForwSol, -54);
    lv_obj_set_y(ui_ServiceStForwSol, 40);
    lv_obj_set_align(ui_ServiceStForwSol, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ServiceStForwSol, "StForwSol");
    lv_obj_set_style_text_color(ui_ServiceStForwSol, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ServiceStForwSol, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ServiceStForwSol, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ServiceValueStForwSol = lv_label_create(ui_ServicePropulsionBox);
    lv_obj_set_width(ui_ServiceValueStForwSol, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ServiceValueStForwSol, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ServiceValueStForwSol, 50);
    lv_obj_set_y(ui_ServiceValueStForwSol, 40);
    lv_obj_set_align(ui_ServiceValueStForwSol, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ServiceValueStForwSol, "0");
    lv_obj_set_style_text_color(ui_ServiceValueStForwSol, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ServiceValueStForwSol, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ServiceValueStForwSol, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ServiceStRevSol = lv_label_create(ui_ServicePropulsionBox);
    lv_obj_set_width(ui_ServiceStRevSol, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ServiceStRevSol, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ServiceStRevSol, -59);
    lv_obj_set_y(ui_ServiceStRevSol, 60);
    lv_obj_set_align(ui_ServiceStRevSol, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ServiceStRevSol, "StRevSol");
    lv_obj_set_style_text_color(ui_ServiceStRevSol, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ServiceStRevSol, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ServiceStRevSol, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ServiceValueStRevSol = lv_label_create(ui_ServicePropulsionBox);
    lv_obj_set_width(ui_ServiceValueStRevSol, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ServiceValueStRevSol, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ServiceValueStRevSol, 50);
    lv_obj_set_y(ui_ServiceValueStRevSol, 60);
    lv_obj_set_align(ui_ServiceValueStRevSol, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ServiceValueStRevSol, "0");
    lv_obj_set_style_text_color(ui_ServiceValueStRevSol, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ServiceValueStRevSol, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ServiceValueStRevSol, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ServiceStClutch = lv_label_create(ui_ServicePropulsionBox);
    lv_obj_set_width(ui_ServiceStClutch, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ServiceStClutch, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ServiceStClutch, -59);
    lv_obj_set_y(ui_ServiceStClutch, 80);
    lv_obj_set_align(ui_ServiceStClutch, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ServiceStClutch, "StClutch");
    lv_obj_set_style_text_color(ui_ServiceStClutch, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ServiceStClutch, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ServiceStClutch, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ServiceValueStClutch = lv_label_create(ui_ServicePropulsionBox);
    lv_obj_set_width(ui_ServiceValueStClutch, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ServiceValueStClutch, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ServiceValueStClutch, 50);
    lv_obj_set_y(ui_ServiceValueStClutch, 80);
    lv_obj_set_align(ui_ServiceValueStClutch, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ServiceValueStClutch, "0");
    lv_obj_set_style_text_color(ui_ServiceValueStClutch, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ServiceValueStClutch, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ServiceValueStClutch, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ServiceGearBox = lv_label_create(ui_ServicePropulsionBox);
    lv_obj_set_width(ui_ServiceGearBox, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ServiceGearBox, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ServiceGearBox, -40);
    lv_obj_set_y(ui_ServiceGearBox, 110);
    lv_obj_set_align(ui_ServiceGearBox, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ServiceGearBox, "GearBox");
    lv_obj_set_style_text_color(ui_ServiceGearBox, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ServiceGearBox, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ServiceGearBox, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ServiceGearBox, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ServiceGearBox, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ServiceGearBox, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ServiceGearBox, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ServiceGBOilPress = lv_label_create(ui_ServicePropulsionBox);
    lv_obj_set_width(ui_ServiceGBOilPress, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ServiceGBOilPress, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ServiceGBOilPress, -47);
    lv_obj_set_y(ui_ServiceGBOilPress, 140);
    lv_obj_set_align(ui_ServiceGBOilPress, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ServiceGBOilPress, "GB Oil Press");
    lv_obj_set_style_text_color(ui_ServiceGBOilPress, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ServiceGBOilPress, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ServiceGBOilPress, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ServiceValueGBOilPress = lv_label_create(ui_ServicePropulsionBox);
    lv_obj_set_width(ui_ServiceValueGBOilPress, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ServiceValueGBOilPress, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ServiceValueGBOilPress, 50);
    lv_obj_set_y(ui_ServiceValueGBOilPress, 140);
    lv_obj_set_align(ui_ServiceValueGBOilPress, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ServiceValueGBOilPress, "0");
    lv_obj_set_style_text_color(ui_ServiceValueGBOilPress, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ServiceValueGBOilPress, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ServiceValueGBOilPress, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ServiceVLoPGB = lv_label_create(ui_ServicePropulsionBox);
    lv_obj_set_width(ui_ServiceVLoPGB, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ServiceVLoPGB, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ServiceVLoPGB, -55);
    lv_obj_set_y(ui_ServiceVLoPGB, 160);
    lv_obj_set_align(ui_ServiceVLoPGB, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ServiceVLoPGB, "V Lo P GB");
    lv_obj_set_style_text_color(ui_ServiceVLoPGB, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ServiceVLoPGB, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ServiceVLoPGB, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ServiceValueVLoPGB = lv_label_create(ui_ServicePropulsionBox);
    lv_obj_set_width(ui_ServiceValueVLoPGB, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ServiceValueVLoPGB, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ServiceValueVLoPGB, 50);
    lv_obj_set_y(ui_ServiceValueVLoPGB, 160);
    lv_obj_set_align(ui_ServiceValueVLoPGB, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ServiceValueVLoPGB, "0");
    lv_obj_set_style_text_color(ui_ServiceValueVLoPGB, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ServiceValueVLoPGB, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ServiceValueVLoPGB, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ServiceStartBlockingBox = lv_obj_create(ui_Service);
    lv_obj_remove_style_all(ui_ServiceStartBlockingBox);
    lv_obj_set_width(ui_ServiceStartBlockingBox, 200);
    lv_obj_set_height(ui_ServiceStartBlockingBox, 362);
    lv_obj_set_x(ui_ServiceStartBlockingBox, 99);
    lv_obj_set_y(ui_ServiceStartBlockingBox, 0);
    lv_obj_set_align(ui_ServiceStartBlockingBox, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ServiceStartBlockingBox, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_ServiceStartBlockingBox, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ServiceStartBlockingBox, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ServiceStartBlockingBox, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ServiceStartBlockingBox, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ServiceStartBlocking = lv_label_create(ui_ServiceStartBlockingBox);
    lv_obj_set_width(ui_ServiceStartBlocking, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ServiceStartBlocking, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ServiceStartBlocking, 0);
    lv_obj_set_y(ui_ServiceStartBlocking, -155);
    lv_obj_set_align(ui_ServiceStartBlocking, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ServiceStartBlocking, "StartBlocking");
    lv_obj_set_style_text_color(ui_ServiceStartBlocking, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ServiceStartBlocking, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ServiceStartBlocking, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BotLineStartBlockingBox = lv_obj_create(ui_ServiceStartBlockingBox);
    lv_obj_remove_style_all(ui_BotLineStartBlockingBox);
    lv_obj_set_width(ui_BotLineStartBlockingBox, 160);
    lv_obj_set_height(ui_BotLineStartBlockingBox, 2);
    lv_obj_set_x(ui_BotLineStartBlockingBox, 0);
    lv_obj_set_y(ui_BotLineStartBlockingBox, -130);
    lv_obj_set_align(ui_BotLineStartBlockingBox, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BotLineStartBlockingBox, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_BotLineStartBlockingBox, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BotLineStartBlockingBox, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BotLineStartBlockingBox, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_BotLineStartBlockingBox, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ServiceSBStClutch = lv_label_create(ui_ServiceStartBlockingBox);
    lv_obj_set_width(ui_ServiceSBStClutch, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ServiceSBStClutch, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ServiceSBStClutch, -59);
    lv_obj_set_y(ui_ServiceSBStClutch, -110);
    lv_obj_set_align(ui_ServiceSBStClutch, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ServiceSBStClutch, "StClutch");
    lv_obj_set_style_text_color(ui_ServiceSBStClutch, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ServiceSBStClutch, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ServiceSBStClutch, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ServiceValueSBStClutchL = lv_label_create(ui_ServiceStartBlockingBox);
    lv_obj_set_width(ui_ServiceValueSBStClutchL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ServiceValueSBStClutchL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ServiceValueSBStClutchL, 40);
    lv_obj_set_y(ui_ServiceValueSBStClutchL, -110);
    lv_obj_set_align(ui_ServiceValueSBStClutchL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ServiceValueSBStClutchL, "0");
    lv_obj_set_style_text_color(ui_ServiceValueSBStClutchL, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ServiceValueSBStClutchL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ServiceValueSBStClutchL, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ServiceValueSBStClutchR = lv_label_create(ui_ServiceStartBlockingBox);
    lv_obj_set_width(ui_ServiceValueSBStClutchR, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ServiceValueSBStClutchR, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ServiceValueSBStClutchR, 80);
    lv_obj_set_y(ui_ServiceValueSBStClutchR, -110);
    lv_obj_set_align(ui_ServiceValueSBStClutchR, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ServiceValueSBStClutchR, "0");
    lv_obj_set_style_text_color(ui_ServiceValueSBStClutchR, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ServiceValueSBStClutchR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ServiceValueSBStClutchR, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ServiceSBStNeutral = lv_label_create(ui_ServiceStartBlockingBox);
    lv_obj_set_width(ui_ServiceSBStNeutral, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ServiceSBStNeutral, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ServiceSBStNeutral, -56);
    lv_obj_set_y(ui_ServiceSBStNeutral, -85);
    lv_obj_set_align(ui_ServiceSBStNeutral, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ServiceSBStNeutral, "StNeutral");
    lv_obj_set_style_text_color(ui_ServiceSBStNeutral, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ServiceSBStNeutral, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ServiceSBStNeutral, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ServiceValueSBStNeutralL = lv_label_create(ui_ServiceStartBlockingBox);
    lv_obj_set_width(ui_ServiceValueSBStNeutralL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ServiceValueSBStNeutralL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ServiceValueSBStNeutralL, 40);
    lv_obj_set_y(ui_ServiceValueSBStNeutralL, -85);
    lv_obj_set_align(ui_ServiceValueSBStNeutralL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ServiceValueSBStNeutralL, "0");
    lv_obj_set_style_text_color(ui_ServiceValueSBStNeutralL, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ServiceValueSBStNeutralL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ServiceValueSBStNeutralL, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ServiceValueSBStNeutralR = lv_label_create(ui_ServiceStartBlockingBox);
    lv_obj_set_width(ui_ServiceValueSBStNeutralR, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ServiceValueSBStNeutralR, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ServiceValueSBStNeutralR, 80);
    lv_obj_set_y(ui_ServiceValueSBStNeutralR, -85);
    lv_obj_set_align(ui_ServiceValueSBStNeutralR, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ServiceValueSBStNeutralR, "0");
    lv_obj_set_style_text_color(ui_ServiceValueSBStNeutralR, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ServiceValueSBStNeutralR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ServiceValueSBStNeutralR, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ServiceSBStTurnGear = lv_label_create(ui_ServiceStartBlockingBox);
    lv_obj_set_width(ui_ServiceSBStTurnGear, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ServiceSBStTurnGear, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ServiceSBStTurnGear, -49);
    lv_obj_set_y(ui_ServiceSBStTurnGear, -60);
    lv_obj_set_align(ui_ServiceSBStTurnGear, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ServiceSBStTurnGear, "StTurnGear");
    lv_obj_set_style_text_color(ui_ServiceSBStTurnGear, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ServiceSBStTurnGear, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ServiceSBStTurnGear, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ServiceValueSBStTurnGearL = lv_label_create(ui_ServiceStartBlockingBox);
    lv_obj_set_width(ui_ServiceValueSBStTurnGearL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ServiceValueSBStTurnGearL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ServiceValueSBStTurnGearL, 40);
    lv_obj_set_y(ui_ServiceValueSBStTurnGearL, -60);
    lv_obj_set_align(ui_ServiceValueSBStTurnGearL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ServiceValueSBStTurnGearL, "0");
    lv_obj_set_style_text_color(ui_ServiceValueSBStTurnGearL, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ServiceValueSBStTurnGearL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ServiceValueSBStTurnGearL, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ServiceValueSBStTurnGearR = lv_label_create(ui_ServiceStartBlockingBox);
    lv_obj_set_width(ui_ServiceValueSBStTurnGearR, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ServiceValueSBStTurnGearR, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ServiceValueSBStTurnGearR, 80);
    lv_obj_set_y(ui_ServiceValueSBStTurnGearR, -60);
    lv_obj_set_align(ui_ServiceValueSBStTurnGearR, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ServiceValueSBStTurnGearR, "0");
    lv_obj_set_style_text_color(ui_ServiceValueSBStTurnGearR, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ServiceValueSBStTurnGearR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ServiceValueSBStTurnGearR, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ServiceSBSpeedReqIdle = lv_label_create(ui_ServiceStartBlockingBox);
    lv_obj_set_width(ui_ServiceSBSpeedReqIdle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ServiceSBSpeedReqIdle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ServiceSBSpeedReqIdle, -39);
    lv_obj_set_y(ui_ServiceSBSpeedReqIdle, -35);
    lv_obj_set_align(ui_ServiceSBSpeedReqIdle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ServiceSBSpeedReqIdle, "SpeedReqIdle");
    lv_obj_set_style_text_color(ui_ServiceSBSpeedReqIdle, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ServiceSBSpeedReqIdle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ServiceSBSpeedReqIdle, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ServiceValueSBSpeedReqIdleL = lv_label_create(ui_ServiceStartBlockingBox);
    lv_obj_set_width(ui_ServiceValueSBSpeedReqIdleL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ServiceValueSBSpeedReqIdleL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ServiceValueSBSpeedReqIdleL, 40);
    lv_obj_set_y(ui_ServiceValueSBSpeedReqIdleL, -35);
    lv_obj_set_align(ui_ServiceValueSBSpeedReqIdleL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ServiceValueSBSpeedReqIdleL, "0");
    lv_obj_set_style_text_color(ui_ServiceValueSBSpeedReqIdleL, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ServiceValueSBSpeedReqIdleL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ServiceValueSBSpeedReqIdleL, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ServiceValueSBSpeedReqIdle = lv_label_create(ui_ServiceStartBlockingBox);
    lv_obj_set_width(ui_ServiceValueSBSpeedReqIdle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ServiceValueSBSpeedReqIdle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ServiceValueSBSpeedReqIdle, 80);
    lv_obj_set_y(ui_ServiceValueSBSpeedReqIdle, -35);
    lv_obj_set_align(ui_ServiceValueSBSpeedReqIdle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ServiceValueSBSpeedReqIdle, "0");
    lv_obj_set_style_text_color(ui_ServiceValueSBSpeedReqIdle, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ServiceValueSBSpeedReqIdle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ServiceValueSBSpeedReqIdle, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ServiceStatistics = lv_label_create(ui_ServiceStartBlockingBox);
    lv_obj_set_width(ui_ServiceStatistics, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ServiceStatistics, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ServiceStatistics, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ServiceStatistics, "Statistics");
    lv_obj_set_style_text_color(ui_ServiceStatistics, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ServiceStatistics, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ServiceStatistics, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BotLineStatistics = lv_obj_create(ui_ServiceStartBlockingBox);
    lv_obj_remove_style_all(ui_BotLineStatistics);
    lv_obj_set_width(ui_BotLineStatistics, 160);
    lv_obj_set_height(ui_BotLineStatistics, 2);
    lv_obj_set_x(ui_BotLineStatistics, 0);
    lv_obj_set_y(ui_BotLineStatistics, 25);
    lv_obj_set_align(ui_BotLineStatistics, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BotLineStatistics, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_BotLineStatistics, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BotLineStatistics, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BotLineStatistics, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_BotLineStatistics, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ServiceNumSuccStarts = lv_label_create(ui_ServiceStartBlockingBox);
    lv_obj_set_width(ui_ServiceNumSuccStarts, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ServiceNumSuccStarts, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ServiceNumSuccStarts, -35);
    lv_obj_set_y(ui_ServiceNumSuccStarts, 40);
    lv_obj_set_align(ui_ServiceNumSuccStarts, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ServiceNumSuccStarts, "NumSuccStarts");
    lv_obj_set_style_text_color(ui_ServiceNumSuccStarts, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ServiceNumSuccStarts, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ServiceNumSuccStarts, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ServiceValueNumSuccStarts = lv_label_create(ui_ServiceStartBlockingBox);
    lv_obj_set_width(ui_ServiceValueNumSuccStarts, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ServiceValueNumSuccStarts, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ServiceValueNumSuccStarts, 60);
    lv_obj_set_y(ui_ServiceValueNumSuccStarts, 40);
    lv_obj_set_align(ui_ServiceValueNumSuccStarts, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ServiceValueNumSuccStarts, "0");
    lv_obj_set_style_text_color(ui_ServiceValueNumSuccStarts, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ServiceValueNumSuccStarts, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ServiceValueNumSuccStarts, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ServiceNumUnscStarts = lv_label_create(ui_ServiceStartBlockingBox);
    lv_obj_set_width(ui_ServiceNumUnscStarts, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ServiceNumUnscStarts, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ServiceNumUnscStarts, -34);
    lv_obj_set_y(ui_ServiceNumUnscStarts, 60);
    lv_obj_set_align(ui_ServiceNumUnscStarts, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ServiceNumUnscStarts, "NumUnscStarts");
    lv_obj_set_style_text_color(ui_ServiceNumUnscStarts, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ServiceNumUnscStarts, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ServiceNumUnscStarts, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ServiceValueNumUnscStarts = lv_label_create(ui_ServiceStartBlockingBox);
    lv_obj_set_width(ui_ServiceValueNumUnscStarts, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ServiceValueNumUnscStarts, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ServiceValueNumUnscStarts, 60);
    lv_obj_set_y(ui_ServiceValueNumUnscStarts, 60);
    lv_obj_set_align(ui_ServiceValueNumUnscStarts, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ServiceValueNumUnscStarts, "0");
    lv_obj_set_style_text_color(ui_ServiceValueNumUnscStarts, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ServiceValueNumUnscStarts, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ServiceValueNumUnscStarts, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ServiceStatisticsDayCons = lv_label_create(ui_ServiceStartBlockingBox);
    lv_obj_set_width(ui_ServiceStatisticsDayCons, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ServiceStatisticsDayCons, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ServiceStatisticsDayCons, -59);
    lv_obj_set_y(ui_ServiceStatisticsDayCons, 90);
    lv_obj_set_align(ui_ServiceStatisticsDayCons, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ServiceStatisticsDayCons, "DayCons");
    lv_obj_set_style_text_color(ui_ServiceStatisticsDayCons, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ServiceStatisticsDayCons, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ServiceStatisticsDayCons, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ServiceValueDayCons = lv_label_create(ui_ServiceStartBlockingBox);
    lv_obj_set_width(ui_ServiceValueDayCons, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ServiceValueDayCons, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ServiceValueDayCons, 60);
    lv_obj_set_y(ui_ServiceValueDayCons, 90);
    lv_obj_set_align(ui_ServiceValueDayCons, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ServiceValueDayCons, "0");
    lv_obj_set_style_text_color(ui_ServiceValueDayCons, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ServiceValueDayCons, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ServiceValueDayCons, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ServiceStatisticsTotFuelUsed = lv_label_create(ui_ServiceStartBlockingBox);
    lv_obj_set_width(ui_ServiceStatisticsTotFuelUsed, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ServiceStatisticsTotFuelUsed, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ServiceStatisticsTotFuelUsed, -39);
    lv_obj_set_y(ui_ServiceStatisticsTotFuelUsed, 110);
    lv_obj_set_align(ui_ServiceStatisticsTotFuelUsed, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ServiceStatisticsTotFuelUsed, "Tot. Fuel Used");
    lv_obj_set_style_text_color(ui_ServiceStatisticsTotFuelUsed, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ServiceStatisticsTotFuelUsed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ServiceStatisticsTotFuelUsed, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ServiceValueTotFuelUsed = lv_label_create(ui_ServiceStartBlockingBox);
    lv_obj_set_width(ui_ServiceValueTotFuelUsed, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ServiceValueTotFuelUsed, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ServiceValueTotFuelUsed, 60);
    lv_obj_set_y(ui_ServiceValueTotFuelUsed, 110);
    lv_obj_set_align(ui_ServiceValueTotFuelUsed, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ServiceValueTotFuelUsed, "0");
    lv_obj_set_style_text_color(ui_ServiceValueTotFuelUsed, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ServiceValueTotFuelUsed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ServiceValueTotFuelUsed, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ServiceStatisticsServiceTime = lv_label_create(ui_ServiceStartBlockingBox);
    lv_obj_set_width(ui_ServiceStatisticsServiceTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ServiceStatisticsServiceTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ServiceStatisticsServiceTime, -45);
    lv_obj_set_y(ui_ServiceStatisticsServiceTime, 140);
    lv_obj_set_align(ui_ServiceStatisticsServiceTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ServiceStatisticsServiceTime, "Service Time");
    lv_obj_set_style_text_color(ui_ServiceStatisticsServiceTime, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ServiceStatisticsServiceTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ServiceStatisticsServiceTime, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ServiceValueServiceTime = lv_label_create(ui_ServiceStartBlockingBox);
    lv_obj_set_width(ui_ServiceValueServiceTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ServiceValueServiceTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ServiceValueServiceTime, 60);
    lv_obj_set_y(ui_ServiceValueServiceTime, 140);
    lv_obj_set_align(ui_ServiceValueServiceTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ServiceValueServiceTime, "0");
    lv_obj_set_style_text_color(ui_ServiceValueServiceTime, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ServiceValueServiceTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ServiceValueServiceTime, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ServiceStatisticsRunHours = lv_label_create(ui_ServiceStartBlockingBox);
    lv_obj_set_width(ui_ServiceStatisticsRunHours, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ServiceStatisticsRunHours, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ServiceStatisticsRunHours, -53);
    lv_obj_set_y(ui_ServiceStatisticsRunHours, 160);
    lv_obj_set_align(ui_ServiceStatisticsRunHours, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ServiceStatisticsRunHours, "Run Hours");
    lv_obj_set_style_text_color(ui_ServiceStatisticsRunHours, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ServiceStatisticsRunHours, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ServiceStatisticsRunHours, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ServiceValueRunHours = lv_label_create(ui_ServiceStartBlockingBox);
    lv_obj_set_width(ui_ServiceValueRunHours, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ServiceValueRunHours, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ServiceValueRunHours, 60);
    lv_obj_set_y(ui_ServiceValueRunHours, 160);
    lv_obj_set_align(ui_ServiceValueRunHours, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ServiceValueRunHours, "0");
    lv_obj_set_style_text_color(ui_ServiceValueRunHours, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ServiceValueRunHours, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ServiceValueRunHours, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ServiceBatteriesBox = lv_obj_create(ui_Service);
    lv_obj_remove_style_all(ui_ServiceBatteriesBox);
    lv_obj_set_width(ui_ServiceBatteriesBox, 180);
    lv_obj_set_height(ui_ServiceBatteriesBox, 362);
    lv_obj_set_x(ui_ServiceBatteriesBox, 287);
    lv_obj_set_y(ui_ServiceBatteriesBox, 0);
    lv_obj_set_align(ui_ServiceBatteriesBox, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ServiceBatteriesBox, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_ServiceBatteriesBox, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ServiceBatteriesBox, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ServiceBatteriesBox, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ServiceBatteriesBox, LV_BORDER_SIDE_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ServiceBatteries = lv_label_create(ui_ServiceBatteriesBox);
    lv_obj_set_width(ui_ServiceBatteries, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ServiceBatteries, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ServiceBatteries, 0);
    lv_obj_set_y(ui_ServiceBatteries, -155);
    lv_obj_set_align(ui_ServiceBatteries, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ServiceBatteries, "Batteries");
    lv_obj_set_style_text_color(ui_ServiceBatteries, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ServiceBatteries, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ServiceBatteries, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BotLineBatteriesBox = lv_obj_create(ui_ServiceBatteriesBox);
    lv_obj_remove_style_all(ui_BotLineBatteriesBox);
    lv_obj_set_width(ui_BotLineBatteriesBox, 160);
    lv_obj_set_height(ui_BotLineBatteriesBox, 2);
    lv_obj_set_x(ui_BotLineBatteriesBox, 0);
    lv_obj_set_y(ui_BotLineBatteriesBox, -130);
    lv_obj_set_align(ui_BotLineBatteriesBox, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BotLineBatteriesBox, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_BotLineBatteriesBox, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BotLineBatteriesBox, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BotLineBatteriesBox, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_BotLineBatteriesBox, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VoltagesBox = lv_obj_create(ui_ServiceBatteriesBox);
    lv_obj_remove_style_all(ui_VoltagesBox);
    lv_obj_set_width(ui_VoltagesBox, 156);
    lv_obj_set_height(ui_VoltagesBox, 298);
    lv_obj_set_x(ui_VoltagesBox, 0);
    lv_obj_set_y(ui_VoltagesBox, 25);
    lv_obj_set_align(ui_VoltagesBox, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_VoltagesBox, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ServiceBatteryVoltages = lv_label_create(ui_VoltagesBox);
    lv_obj_set_width(ui_ServiceBatteryVoltages, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ServiceBatteryVoltages, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ServiceBatteryVoltages, -34);
    lv_obj_set_y(ui_ServiceBatteryVoltages, -137);
    lv_obj_set_align(ui_ServiceBatteryVoltages, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ServiceBatteryVoltages, "Voltages");
    lv_obj_set_style_text_color(ui_ServiceBatteryVoltages, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ServiceBatteryVoltages, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ServiceBatteryVoltages, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ServiceBatteriesBar = lv_bar_create(ui_VoltagesBox);
    lv_bar_set_value(ui_ServiceBatteriesBar, 10, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_ServiceBatteriesBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_ServiceBatteriesBar, 20);
    lv_obj_set_height(ui_ServiceBatteriesBar, 200);
    lv_obj_set_x(ui_ServiceBatteriesBar, 0);
    lv_obj_set_y(ui_ServiceBatteriesBar, -20);
    lv_obj_set_align(ui_ServiceBatteriesBar, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_ServiceBatteriesBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ServiceBatteriesBar, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ServiceBatteriesBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ServiceBatteriesBar, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ServiceBatteriesBar, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_ServiceBatteriesBar, 1, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_ServiceValueBatteryVolt = lv_label_create(ui_VoltagesBox);
    lv_obj_set_width(ui_ServiceValueBatteryVolt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ServiceValueBatteryVolt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ServiceValueBatteryVolt, -9);
    lv_obj_set_y(ui_ServiceValueBatteryVolt, 107);
    lv_obj_set_align(ui_ServiceValueBatteryVolt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ServiceValueBatteryVolt, "10");
    lv_obj_set_style_text_color(ui_ServiceValueBatteryVolt, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ServiceValueBatteryVolt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ServiceValueBatteryVolt, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ServiceValueBatteryVolt, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ServiceUnitBatteryVolt = lv_label_create(ui_VoltagesBox);
    lv_obj_set_width(ui_ServiceUnitBatteryVolt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ServiceUnitBatteryVolt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ServiceUnitBatteryVolt, 25);
    lv_obj_set_y(ui_ServiceUnitBatteryVolt, 110);
    lv_obj_set_align(ui_ServiceUnitBatteryVolt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ServiceUnitBatteryVolt, "V");
    lv_obj_set_style_text_color(ui_ServiceUnitBatteryVolt, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ServiceUnitBatteryVolt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ServiceUnitBatteryVolt, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ServiceBatteryVolt = lv_label_create(ui_VoltagesBox);
    lv_obj_set_width(ui_ServiceBatteryVolt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ServiceBatteryVolt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ServiceBatteryVolt, 0);
    lv_obj_set_y(ui_ServiceBatteryVolt, 135);
    lv_obj_set_align(ui_ServiceBatteryVolt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ServiceBatteryVolt, "Battery Volt");
    lv_obj_set_style_text_color(ui_ServiceBatteryVolt, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ServiceBatteryVolt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ServiceBatteryVolt, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BatteriesLine100 = lv_obj_create(ui_VoltagesBox);
    lv_obj_remove_style_all(ui_BatteriesLine100);
    lv_obj_set_width(ui_BatteriesLine100, 30);
    lv_obj_set_height(ui_BatteriesLine100, 2);
    lv_obj_set_x(ui_BatteriesLine100, 25);
    lv_obj_set_y(ui_BatteriesLine100, -119);
    lv_obj_set_align(ui_BatteriesLine100, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BatteriesLine100, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_BatteriesLine100, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BatteriesLine100, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BatteriesLine100, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_BatteriesLine100, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ServiceUnitBatteryVoltBar100 = lv_label_create(ui_VoltagesBox);
    lv_obj_set_width(ui_ServiceUnitBatteryVoltBar100, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ServiceUnitBatteryVoltBar100, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ServiceUnitBatteryVoltBar100, 55);
    lv_obj_set_y(ui_ServiceUnitBatteryVoltBar100, -120);
    lv_obj_set_align(ui_ServiceUnitBatteryVoltBar100, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ServiceUnitBatteryVoltBar100, "100");
    lv_obj_set_style_text_color(ui_ServiceUnitBatteryVoltBar100, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ServiceUnitBatteryVoltBar100, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ServiceUnitBatteryVoltBar100, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BatteriesLine90 = lv_obj_create(ui_VoltagesBox);
    lv_obj_remove_style_all(ui_BatteriesLine90);
    lv_obj_set_width(ui_BatteriesLine90, 30);
    lv_obj_set_height(ui_BatteriesLine90, 2);
    lv_obj_set_x(ui_BatteriesLine90, 25);
    lv_obj_set_y(ui_BatteriesLine90, -100);
    lv_obj_set_align(ui_BatteriesLine90, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BatteriesLine90, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_BatteriesLine90, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BatteriesLine90, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BatteriesLine90, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_BatteriesLine90, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ServiceUnitBatteryVoltBar90 = lv_label_create(ui_VoltagesBox);
    lv_obj_set_width(ui_ServiceUnitBatteryVoltBar90, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ServiceUnitBatteryVoltBar90, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ServiceUnitBatteryVoltBar90, 55);
    lv_obj_set_y(ui_ServiceUnitBatteryVoltBar90, -100);
    lv_obj_set_align(ui_ServiceUnitBatteryVoltBar90, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ServiceUnitBatteryVoltBar90, "90");
    lv_obj_set_style_text_color(ui_ServiceUnitBatteryVoltBar90, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ServiceUnitBatteryVoltBar90, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ServiceUnitBatteryVoltBar90, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BatteriesLine80 = lv_obj_create(ui_VoltagesBox);
    lv_obj_remove_style_all(ui_BatteriesLine80);
    lv_obj_set_width(ui_BatteriesLine80, 30);
    lv_obj_set_height(ui_BatteriesLine80, 2);
    lv_obj_set_x(ui_BatteriesLine80, 25);
    lv_obj_set_y(ui_BatteriesLine80, -80);
    lv_obj_set_align(ui_BatteriesLine80, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BatteriesLine80, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_BatteriesLine80, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BatteriesLine80, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BatteriesLine80, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_BatteriesLine80, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ServiceUnitBatteryVoltBar80 = lv_label_create(ui_VoltagesBox);
    lv_obj_set_width(ui_ServiceUnitBatteryVoltBar80, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ServiceUnitBatteryVoltBar80, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_x(ui_ServiceUnitBatteryVoltBar80, 55);
    lv_obj_set_y(ui_ServiceUnitBatteryVoltBar80, -80);
    lv_obj_set_align(ui_ServiceUnitBatteryVoltBar80, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ServiceUnitBatteryVoltBar80, "80");
    lv_obj_set_style_text_color(ui_ServiceUnitBatteryVoltBar80, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ServiceUnitBatteryVoltBar80, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ServiceUnitBatteryVoltBar80, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BatteriesLine70 = lv_obj_create(ui_VoltagesBox);
    lv_obj_remove_style_all(ui_BatteriesLine70);
    lv_obj_set_width(ui_BatteriesLine70, 30);
    lv_obj_set_height(ui_BatteriesLine70, 2);
    lv_obj_set_x(ui_BatteriesLine70, 25);
    lv_obj_set_y(ui_BatteriesLine70, -60);
    lv_obj_set_align(ui_BatteriesLine70, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BatteriesLine70, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_BatteriesLine70, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BatteriesLine70, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BatteriesLine70, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_BatteriesLine70, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ServiceUnitBatteryVoltBar70 = lv_label_create(ui_VoltagesBox);
    lv_obj_set_width(ui_ServiceUnitBatteryVoltBar70, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ServiceUnitBatteryVoltBar70, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_x(ui_ServiceUnitBatteryVoltBar70, 55);
    lv_obj_set_y(ui_ServiceUnitBatteryVoltBar70, -60);
    lv_obj_set_align(ui_ServiceUnitBatteryVoltBar70, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ServiceUnitBatteryVoltBar70, "70");
    lv_obj_set_style_text_color(ui_ServiceUnitBatteryVoltBar70, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ServiceUnitBatteryVoltBar70, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ServiceUnitBatteryVoltBar70, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BatteriesLine60 = lv_obj_create(ui_VoltagesBox);
    lv_obj_remove_style_all(ui_BatteriesLine60);
    lv_obj_set_width(ui_BatteriesLine60, 30);
    lv_obj_set_height(ui_BatteriesLine60, 2);
    lv_obj_set_x(ui_BatteriesLine60, 25);
    lv_obj_set_y(ui_BatteriesLine60, -40);
    lv_obj_set_align(ui_BatteriesLine60, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BatteriesLine60, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_BatteriesLine60, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BatteriesLine60, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BatteriesLine60, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_BatteriesLine60, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ServiceUnitBatteryVoltBar60 = lv_label_create(ui_VoltagesBox);
    lv_obj_set_width(ui_ServiceUnitBatteryVoltBar60, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ServiceUnitBatteryVoltBar60, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_x(ui_ServiceUnitBatteryVoltBar60, 55);
    lv_obj_set_y(ui_ServiceUnitBatteryVoltBar60, -40);
    lv_obj_set_align(ui_ServiceUnitBatteryVoltBar60, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ServiceUnitBatteryVoltBar60, "60");
    lv_obj_set_style_text_color(ui_ServiceUnitBatteryVoltBar60, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ServiceUnitBatteryVoltBar60, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ServiceUnitBatteryVoltBar60, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BatteriesLine50 = lv_obj_create(ui_VoltagesBox);
    lv_obj_remove_style_all(ui_BatteriesLine50);
    lv_obj_set_width(ui_BatteriesLine50, 30);
    lv_obj_set_height(ui_BatteriesLine50, 2);
    lv_obj_set_x(ui_BatteriesLine50, 25);
    lv_obj_set_y(ui_BatteriesLine50, -20);
    lv_obj_set_align(ui_BatteriesLine50, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BatteriesLine50, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_BatteriesLine50, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BatteriesLine50, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BatteriesLine50, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_BatteriesLine50, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ServiceUnitBatteryVoltBar50 = lv_label_create(ui_VoltagesBox);
    lv_obj_set_width(ui_ServiceUnitBatteryVoltBar50, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ServiceUnitBatteryVoltBar50, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_x(ui_ServiceUnitBatteryVoltBar50, 55);
    lv_obj_set_y(ui_ServiceUnitBatteryVoltBar50, -20);
    lv_obj_set_align(ui_ServiceUnitBatteryVoltBar50, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ServiceUnitBatteryVoltBar50, "50");
    lv_obj_set_style_text_color(ui_ServiceUnitBatteryVoltBar50, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ServiceUnitBatteryVoltBar50, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ServiceUnitBatteryVoltBar50, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BatteriesLine40 = lv_obj_create(ui_VoltagesBox);
    lv_obj_remove_style_all(ui_BatteriesLine40);
    lv_obj_set_width(ui_BatteriesLine40, 30);
    lv_obj_set_height(ui_BatteriesLine40, 2);
    lv_obj_set_x(ui_BatteriesLine40, 25);
    lv_obj_set_y(ui_BatteriesLine40, 0);
    lv_obj_set_align(ui_BatteriesLine40, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BatteriesLine40, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_BatteriesLine40, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BatteriesLine40, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BatteriesLine40, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_BatteriesLine40, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ServiceUnitBatteryVoltBar40 = lv_label_create(ui_VoltagesBox);
    lv_obj_set_width(ui_ServiceUnitBatteryVoltBar40, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ServiceUnitBatteryVoltBar40, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_x(ui_ServiceUnitBatteryVoltBar40, 55);
    lv_obj_set_y(ui_ServiceUnitBatteryVoltBar40, 0);
    lv_obj_set_align(ui_ServiceUnitBatteryVoltBar40, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ServiceUnitBatteryVoltBar40, "40");
    lv_obj_set_style_text_color(ui_ServiceUnitBatteryVoltBar40, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ServiceUnitBatteryVoltBar40, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ServiceUnitBatteryVoltBar40, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BatteriesLine30 = lv_obj_create(ui_VoltagesBox);
    lv_obj_remove_style_all(ui_BatteriesLine30);
    lv_obj_set_width(ui_BatteriesLine30, 30);
    lv_obj_set_height(ui_BatteriesLine30, 2);
    lv_obj_set_x(ui_BatteriesLine30, 25);
    lv_obj_set_y(ui_BatteriesLine30, 20);
    lv_obj_set_align(ui_BatteriesLine30, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BatteriesLine30, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_BatteriesLine30, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BatteriesLine30, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BatteriesLine30, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_BatteriesLine30, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ServiceUnitBatteryVoltBar30 = lv_label_create(ui_VoltagesBox);
    lv_obj_set_width(ui_ServiceUnitBatteryVoltBar30, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ServiceUnitBatteryVoltBar30, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_x(ui_ServiceUnitBatteryVoltBar30, 55);
    lv_obj_set_y(ui_ServiceUnitBatteryVoltBar30, 20);
    lv_obj_set_align(ui_ServiceUnitBatteryVoltBar30, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ServiceUnitBatteryVoltBar30, "30");
    lv_obj_set_style_text_color(ui_ServiceUnitBatteryVoltBar30, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ServiceUnitBatteryVoltBar30, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ServiceUnitBatteryVoltBar30, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BatteriesLine20 = lv_obj_create(ui_VoltagesBox);
    lv_obj_remove_style_all(ui_BatteriesLine20);
    lv_obj_set_width(ui_BatteriesLine20, 30);
    lv_obj_set_height(ui_BatteriesLine20, 2);
    lv_obj_set_x(ui_BatteriesLine20, 25);
    lv_obj_set_y(ui_BatteriesLine20, 40);
    lv_obj_set_align(ui_BatteriesLine20, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BatteriesLine20, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_BatteriesLine20, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BatteriesLine20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BatteriesLine20, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_BatteriesLine20, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ServiceUnitBatteryVoltBar20 = lv_label_create(ui_VoltagesBox);
    lv_obj_set_width(ui_ServiceUnitBatteryVoltBar20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ServiceUnitBatteryVoltBar20, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_x(ui_ServiceUnitBatteryVoltBar20, 55);
    lv_obj_set_y(ui_ServiceUnitBatteryVoltBar20, 40);
    lv_obj_set_align(ui_ServiceUnitBatteryVoltBar20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ServiceUnitBatteryVoltBar20, "20");
    lv_obj_set_style_text_color(ui_ServiceUnitBatteryVoltBar20, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ServiceUnitBatteryVoltBar20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ServiceUnitBatteryVoltBar20, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BatteriesLine10 = lv_obj_create(ui_VoltagesBox);
    lv_obj_remove_style_all(ui_BatteriesLine10);
    lv_obj_set_width(ui_BatteriesLine10, 30);
    lv_obj_set_height(ui_BatteriesLine10, 2);
    lv_obj_set_x(ui_BatteriesLine10, 25);
    lv_obj_set_y(ui_BatteriesLine10, 60);
    lv_obj_set_align(ui_BatteriesLine10, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BatteriesLine10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_BatteriesLine10, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BatteriesLine10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BatteriesLine10, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_BatteriesLine10, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ServiceUnitBatteryVoltBar10 = lv_label_create(ui_VoltagesBox);
    lv_obj_set_width(ui_ServiceUnitBatteryVoltBar10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ServiceUnitBatteryVoltBar10, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_x(ui_ServiceUnitBatteryVoltBar10, 55);
    lv_obj_set_y(ui_ServiceUnitBatteryVoltBar10, 60);
    lv_obj_set_align(ui_ServiceUnitBatteryVoltBar10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ServiceUnitBatteryVoltBar10, "10");
    lv_obj_set_style_text_color(ui_ServiceUnitBatteryVoltBar10, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ServiceUnitBatteryVoltBar10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ServiceUnitBatteryVoltBar10, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BatteriesLine0 = lv_obj_create(ui_VoltagesBox);
    lv_obj_remove_style_all(ui_BatteriesLine0);
    lv_obj_set_width(ui_BatteriesLine0, 30);
    lv_obj_set_height(ui_BatteriesLine0, 2);
    lv_obj_set_x(ui_BatteriesLine0, 25);
    lv_obj_set_y(ui_BatteriesLine0, 80);
    lv_obj_set_align(ui_BatteriesLine0, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BatteriesLine0, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_BatteriesLine0, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BatteriesLine0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BatteriesLine0, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_BatteriesLine0, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ServiceUnitBatteryVoltBar0 = lv_label_create(ui_VoltagesBox);
    lv_obj_set_width(ui_ServiceUnitBatteryVoltBar0, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ServiceUnitBatteryVoltBar0, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_x(ui_ServiceUnitBatteryVoltBar0, 55);
    lv_obj_set_y(ui_ServiceUnitBatteryVoltBar0, 80);
    lv_obj_set_align(ui_ServiceUnitBatteryVoltBar0, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ServiceUnitBatteryVoltBar0, "0");
    lv_obj_set_style_text_color(ui_ServiceUnitBatteryVoltBar0, lv_color_hex(0x3FDD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ServiceUnitBatteryVoltBar0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ServiceUnitBatteryVoltBar0, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IncrementBar = lv_btn_create(ui_Service);
    lv_obj_set_width(ui_IncrementBar, 74);
    lv_obj_set_height(ui_IncrementBar, 41);
    lv_obj_set_x(ui_IncrementBar, 339);
    lv_obj_set_y(ui_IncrementBar, 209);
    lv_obj_set_align(ui_IncrementBar, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_IncrementBar, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_IncrementBar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DecrementBar = lv_btn_create(ui_Service);
    lv_obj_set_width(ui_DecrementBar, 74);
    lv_obj_set_height(ui_DecrementBar, 41);
    lv_obj_set_x(ui_DecrementBar, 250);
    lv_obj_set_y(ui_DecrementBar, 209);
    lv_obj_set_align(ui_DecrementBar, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DecrementBar, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_DecrementBar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_DecrementBar, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DecrementBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_IncrementBar, ui_event_IncrementBar, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DecrementBar, ui_event_DecrementBar, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Service, ui_event_SlideScreen, LV_EVENT_ALL, NULL);

}
