// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: P2

#include <stdio.h>
#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Home
void ui_Home_screen_init(void);
lv_obj_t * ui_Home;
lv_obj_t * ui_HomeHeader;
lv_obj_t * ui_HomeTopLine;
lv_obj_t * ui_HomeBotLine;
lv_obj_t * ui_HomeSpeedBox;
lv_obj_t * ui_HomeValueRPM;
lv_obj_t * ui_HomeUnitRPM;
lv_obj_t * ui_HomeSpeedRPM;
lv_obj_t * ui_HomeFuelRateBox;
lv_obj_t * ui_HomeValueFuelRate;
lv_obj_t * ui_HomeUnitFuelRate;
lv_obj_t * ui_HomeFuelRate;
lv_obj_t * ui_HomeLoadBox;
lv_obj_t * ui_HomeValueLoad;
lv_obj_t * ui_HomeUnitLoad;
lv_obj_t * ui_HomeLoad;
lv_obj_t * ui_HomeOilPresBox;
lv_obj_t * ui_HomeValueOilPress;
lv_obj_t * ui_HomeUnitOilPress;
lv_obj_t * ui_HomeOilPress;
lv_obj_t * ui_HomeOilTempBox;
lv_obj_t * ui_HomeValueOilTemp;
lv_obj_t * ui_HomeUnitOilTemp;
lv_obj_t * ui_HomeOilTemp;
lv_obj_t * ui_HomeCoolTempBox;
lv_obj_t * ui_HomeValueCoolTemp;
lv_obj_t * ui_HomeUnitCoolTemp;
lv_obj_t * ui_HomeCoolTemp;
lv_obj_t * ui_HomeIntakePressBox;
lv_obj_t * ui_HomeValueIntakePress;
lv_obj_t * ui_HomeUnitIntakePress;
lv_obj_t * ui_HomeIntakePress;
lv_obj_t * ui_HomeIntakeTempBox;
lv_obj_t * ui_HomeValueIntakeTemp;
lv_obj_t * ui_HomeUnitIntakeTemp;
lv_obj_t * ui_HomeIntakeTemp;
lv_obj_t * ui_HomeExhaustTempBox;
lv_obj_t * ui_HomeValueExhaustTemp;
lv_obj_t * ui_HomeUnitExhaustTemp;
lv_obj_t * ui_HomeExhaustTemp;
lv_obj_t * ui_HomeStatusBox;
lv_obj_t * ui_HomeStatus;
lv_obj_t * ui_HomeECUStatusBox;
lv_obj_t * ui_HomeEcuStatus;
lv_obj_t * ui_HomePWRLimit;
lv_obj_t * ui_HomeBatteryVolt;
lv_obj_t * ui_HomeServiceTime;
lv_obj_t * ui_HomeRunHours;
lv_obj_t * ui_HomeDayCons;
lv_obj_t * ui_HomeValueBatteryVolt;
lv_obj_t * ui_HomeValueServiceTime;
lv_obj_t * ui_HomeValueRunHours;
lv_obj_t * ui_HomeValueDayCons;
lv_obj_t * ui_HomeUnitBatteryVolt;
lv_obj_t * ui_HomeUnitServiceTime;
lv_obj_t * ui_HomeUnitRunHours;
lv_obj_t * ui_HomeRTCBox;
lv_obj_t * ui_HomeDeviceType;
lv_obj_t * ui_HomeTime;
lv_obj_t * ui_HomeBotLineRTC;
lv_obj_t * ui_HomeDate;


// SCREEN: ui_Service
void ui_Service_screen_init(void);
lv_obj_t * ui_Service;
lv_obj_t * ui_ServiceHeader;
lv_obj_t * ui_ServiceTopLine;
lv_obj_t * ui_ServiceBotLine;
lv_obj_t * ui_ServiceRPMBox;
lv_obj_t * ui_TopLineRPMBox;
lv_obj_t * ui_BotLineRPMBox;
lv_obj_t * ui_ServiceRPM;
lv_obj_t * ui_ServiceSpeedToECU;
lv_obj_t * ui_ServiceValueSpeedToECU;
lv_obj_t * ui_ServiceUnitSpeedToECU;
lv_obj_t * ui_ServiceSpeedRequest;
lv_obj_t * ui_ServiceValueSpeedRequest;
lv_obj_t * ui_ServiceUnitSpeedRequest;
lv_obj_t * ui_ServiceLoad;
lv_obj_t * ui_ServiceValueLoad;
lv_obj_t * ui_ServiceUnitLoad;
lv_obj_t * ui_ServicePropulsionBox;
lv_obj_t * ui_BotLinePropulsionBox;
lv_obj_t * ui_ServicePropulsion;
lv_obj_t * ui_ServiceLever;
lv_obj_t * ui_ServiceForwardPos;
lv_obj_t * ui_ServiceValueForwardPos;
lv_obj_t * ui_ServiceReversePos;
lv_obj_t * ui_ServiceValueReversePos;
lv_obj_t * ui_ServiceStNeutral;
lv_obj_t * ui_ServiceValueStNeutral;
lv_obj_t * ui_ServiceLeverPosition;
lv_obj_t * ui_ServiceValueLeverPosition;
lv_obj_t * ui_ServiceState;
lv_obj_t * ui_ServiceStForwSol;
lv_obj_t * ui_ServiceValueStForwSol;
lv_obj_t * ui_ServiceStRevSol;
lv_obj_t * ui_ServiceValueStRevSol;
lv_obj_t * ui_ServiceStClutch;
lv_obj_t * ui_ServiceValueStClutch;
lv_obj_t * ui_ServiceGearBox;
lv_obj_t * ui_ServiceGBOilPress;
lv_obj_t * ui_ServiceValueGBOilPress;
lv_obj_t * ui_ServiceVLoPGB;
lv_obj_t * ui_ServiceValueVLoPGB;
lv_obj_t * ui_ServiceStartBlockingBox;
lv_obj_t * ui_ServiceStartBlocking;
lv_obj_t * ui_BotLineStartBlockingBox;
lv_obj_t * ui_ServiceSBStClutch;
lv_obj_t * ui_ServiceValueSBStClutchL;
lv_obj_t * ui_ServiceValueSBStClutchR;
lv_obj_t * ui_ServiceSBStNeutral;
lv_obj_t * ui_ServiceValueSBStNeutralL;
lv_obj_t * ui_ServiceValueSBStNeutralR;
lv_obj_t * ui_ServiceSBStTurnGear;
lv_obj_t * ui_ServiceValueSBStTurnGearL;
lv_obj_t * ui_ServiceValueSBStTurnGearR;
lv_obj_t * ui_ServiceSBSpeedReqIdle;
lv_obj_t * ui_ServiceValueSBSpeedReqIdleL;
lv_obj_t * ui_ServiceValueSBSpeedReqIdle;
lv_obj_t * ui_ServiceStatistics;
lv_obj_t * ui_BotLineStatistics;
lv_obj_t * ui_ServiceNumSuccStarts;
lv_obj_t * ui_ServiceValueNumSuccStarts;
lv_obj_t * ui_ServiceNumUnscStarts;
lv_obj_t * ui_ServiceValueNumUnscStarts;
lv_obj_t * ui_ServiceStatisticsDayCons;
lv_obj_t * ui_ServiceValueDayCons;
lv_obj_t * ui_ServiceStatisticsTotFuelUsed;
lv_obj_t * ui_ServiceValueTotFuelUsed;
lv_obj_t * ui_ServiceStatisticsServiceTime;
lv_obj_t * ui_ServiceValueServiceTime;
lv_obj_t * ui_ServiceStatisticsRunHours;
lv_obj_t * ui_ServiceValueRunHours;
lv_obj_t * ui_ServiceBatteriesBox;
lv_obj_t * ui_ServiceBatteries;
lv_obj_t * ui_BotLineBatteriesBox;
lv_obj_t * ui_VoltagesBox;
lv_obj_t * ui_ServiceBatteryVoltages;
lv_obj_t * ui_ServiceBatteriesBar;
lv_obj_t * ui_ServiceValueBatteryVolt;
lv_obj_t * ui_ServiceUnitBatteryVolt;
lv_obj_t * ui_ServiceBatteryVolt;
lv_obj_t * ui_BatteriesLine100;
lv_obj_t * ui_ServiceUnitBatteryVoltBar100;
lv_obj_t * ui_BatteriesLine90;
lv_obj_t * ui_ServiceUnitBatteryVoltBar90;
lv_obj_t * ui_BatteriesLine80;
lv_obj_t * ui_ServiceUnitBatteryVoltBar80;
lv_obj_t * ui_BatteriesLine70;
lv_obj_t * ui_ServiceUnitBatteryVoltBar70;
lv_obj_t * ui_BatteriesLine60;
lv_obj_t * ui_ServiceUnitBatteryVoltBar60;
lv_obj_t * ui_BatteriesLine50;
lv_obj_t * ui_ServiceUnitBatteryVoltBar50;
lv_obj_t * ui_BatteriesLine40;
lv_obj_t * ui_ServiceUnitBatteryVoltBar40;
lv_obj_t * ui_BatteriesLine30;
lv_obj_t * ui_ServiceUnitBatteryVoltBar30;
lv_obj_t * ui_BatteriesLine20;
lv_obj_t * ui_ServiceUnitBatteryVoltBar20;
lv_obj_t * ui_BatteriesLine10;
lv_obj_t * ui_ServiceUnitBatteryVoltBar10;
lv_obj_t * ui_BatteriesLine0;
lv_obj_t * ui_ServiceUnitBatteryVoltBar0;
void ui_event_IncrementBar(lv_event_t * e);
lv_obj_t * ui_IncrementBar;
void ui_event_DecrementBar(lv_event_t * e);
lv_obj_t * ui_DecrementBar;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_SlideScreen(lv_event_t * e){
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Service, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Service_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        if(lv_obj_has_flag(ui_Home, LV_OBJ_FLAG_CHECKABLE)){
        _ui_screen_change(&ui_Service, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Service_screen_init);
        _ui_flag_modify(ui_Home, LV_OBJ_FLAG_CHECKABLE, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_Service, LV_OBJ_FLAG_CHECKABLE, _UI_MODIFY_FLAG_ADD);
        }
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT){
        lv_indev_wait_release(lv_indev_get_act());
        if(lv_obj_has_flag(ui_Service, LV_OBJ_FLAG_CHECKABLE)){
        _ui_screen_change(&ui_Home, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Service_screen_init);
        _ui_flag_modify(ui_Service, LV_OBJ_FLAG_CHECKABLE, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_Home, LV_OBJ_FLAG_CHECKABLE, _UI_MODIFY_FLAG_ADD);
        }
    }
}

void ui_event_IncrementBar(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        _ui_bar_increment(ui_ServiceBatteriesBar, 1, LV_ANIM_ON);
    }
}
void ui_event_DecrementBar(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        _ui_bar_increment(ui_ServiceBatteriesBar, -1, LV_ANIM_ON);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Home_screen_init();
    ui_Service_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Home);
}
