// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: P2

#ifndef _P2_UI_H
#define _P2_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

extern uint8_t BrightnessLevel;
extern bool ChangeBrightnessFlag;

extern uint8_t BarValue;
extern bool ChangeBarFlag;

// SCREEN: ui_Home
void ui_Home_screen_init(void);
void ui_event_SlideScreen(lv_event_t * e);
extern lv_obj_t * ui_Home;
extern lv_obj_t * ui_HomeHeader;
extern lv_obj_t * ui_HomeTopLine;
extern lv_obj_t * ui_HomeBotLine;
extern lv_obj_t * ui_HomeSpeedBox;
extern lv_obj_t * ui_HomeValueRPM;
extern lv_obj_t * ui_HomeUnitRPM;
extern lv_obj_t * ui_HomeSpeedRPM;
extern lv_obj_t * ui_HomeFuelRateBox;
extern lv_obj_t * ui_HomeValueFuelRate;
extern lv_obj_t * ui_HomeUnitFuelRate;
extern lv_obj_t * ui_HomeFuelRate;
extern lv_obj_t * ui_HomeLoadBox;
extern lv_obj_t * ui_HomeValueLoad;
extern lv_obj_t * ui_HomeUnitLoad;
extern lv_obj_t * ui_HomeLoad;
extern lv_obj_t * ui_HomeOilPresBox;
extern lv_obj_t * ui_HomeValueOilPress;
extern lv_obj_t * ui_HomeUnitOilPress;
extern lv_obj_t * ui_HomeOilPress;
extern lv_obj_t * ui_HomeOilTempBox;
extern lv_obj_t * ui_HomeValueOilTemp;
extern lv_obj_t * ui_HomeUnitOilTemp;
extern lv_obj_t * ui_HomeOilTemp;
extern lv_obj_t * ui_HomeCoolTempBox;
extern lv_obj_t * ui_HomeValueCoolTemp;
extern lv_obj_t * ui_HomeUnitCoolTemp;
extern lv_obj_t * ui_HomeCoolTemp;
extern lv_obj_t * ui_HomeIntakePressBox;
extern lv_obj_t * ui_HomeValueIntakePress;
extern lv_obj_t * ui_HomeUnitIntakePress;
extern lv_obj_t * ui_HomeIntakePress;
extern lv_obj_t * ui_HomeIntakeTempBox;
extern lv_obj_t * ui_HomeValueIntakeTemp;
extern lv_obj_t * ui_HomeUnitIntakeTemp;
extern lv_obj_t * ui_HomeIntakeTemp;
extern lv_obj_t * ui_HomeExhaustTempBox;
extern lv_obj_t * ui_HomeValueExhaustTemp;
extern lv_obj_t * ui_HomeUnitExhaustTemp;
extern lv_obj_t * ui_HomeExhaustTemp;
extern lv_obj_t * ui_HomeStatusBox;
extern lv_obj_t * ui_HomeStatus;
extern lv_obj_t * ui_HomeECUStatusBox;
extern lv_obj_t * ui_HomeEcuStatus;
extern lv_obj_t * ui_HomePWRLimit;
extern lv_obj_t * ui_HomeBatteryVolt;
extern lv_obj_t * ui_HomeServiceTime;
extern lv_obj_t * ui_HomeRunHours;
extern lv_obj_t * ui_HomeDayCons;
extern lv_obj_t * ui_HomeValueBatteryVolt;
extern lv_obj_t * ui_HomeValueServiceTime;
extern lv_obj_t * ui_HomeValueRunHours;
extern lv_obj_t * ui_HomeValueDayCons;
extern lv_obj_t * ui_HomeUnitBatteryVolt;
extern lv_obj_t * ui_HomeUnitServiceTime;
extern lv_obj_t * ui_HomeUnitRunHours;
extern lv_obj_t * ui_HomeRTCBox;
extern lv_obj_t * ui_HomeDeviceType;
extern lv_obj_t * ui_HomeTime;
extern lv_obj_t * ui_HomeBotLineRTC;
extern lv_obj_t * ui_HomeDate;
// SCREEN: ui_Service
void ui_Service_screen_init(void);
extern lv_obj_t * ui_Service;
extern lv_obj_t * ui_ServiceHeader;
extern lv_obj_t * ui_ServiceTopLine;
extern lv_obj_t * ui_ServiceBotLine;
extern lv_obj_t * ui_ServiceRPMBox;
extern lv_obj_t * ui_TopLineRPMBox;
extern lv_obj_t * ui_BotLineRPMBox;
extern lv_obj_t * ui_ServiceRPM;
extern lv_obj_t * ui_ServiceSpeedToECU;
extern lv_obj_t * ui_ServiceValueSpeedToECU;
extern lv_obj_t * ui_ServiceUnitSpeedToECU;
extern lv_obj_t * ui_ServiceSpeedRequest;
extern lv_obj_t * ui_ServiceValueSpeedRequest;
extern lv_obj_t * ui_ServiceUnitSpeedRequest;
extern lv_obj_t * ui_ServiceLoad;
extern lv_obj_t * ui_ServiceValueLoad;
extern lv_obj_t * ui_ServiceUnitLoad;
extern lv_obj_t * ui_ServicePropulsionBox;
extern lv_obj_t * ui_BotLinePropulsionBox;
extern lv_obj_t * ui_ServicePropulsion;
extern lv_obj_t * ui_ServiceLever;
extern lv_obj_t * ui_ServiceForwardPos;
extern lv_obj_t * ui_ServiceValueForwardPos;
extern lv_obj_t * ui_ServiceReversePos;
extern lv_obj_t * ui_ServiceValueReversePos;
extern lv_obj_t * ui_ServiceStNeutral;
extern lv_obj_t * ui_ServiceValueStNeutral;
extern lv_obj_t * ui_ServiceLeverPosition;
extern lv_obj_t * ui_ServiceValueLeverPosition;
extern lv_obj_t * ui_ServiceState;
extern lv_obj_t * ui_ServiceStForwSol;
extern lv_obj_t * ui_ServiceValueStForwSol;
extern lv_obj_t * ui_ServiceStRevSol;
extern lv_obj_t * ui_ServiceValueStRevSol;
extern lv_obj_t * ui_ServiceStClutch;
extern lv_obj_t * ui_ServiceValueStClutch;
extern lv_obj_t * ui_ServiceGearBox;
extern lv_obj_t * ui_ServiceGBOilPress;
extern lv_obj_t * ui_ServiceValueGBOilPress;
extern lv_obj_t * ui_ServiceVLoPGB;
extern lv_obj_t * ui_ServiceValueVLoPGB;
extern lv_obj_t * ui_ServiceStartBlockingBox;
extern lv_obj_t * ui_ServiceStartBlocking;
extern lv_obj_t * ui_BotLineStartBlockingBox;
extern lv_obj_t * ui_ServiceSBStClutch;
extern lv_obj_t * ui_ServiceValueSBStClutchL;
extern lv_obj_t * ui_ServiceValueSBStClutchR;
extern lv_obj_t * ui_ServiceSBStNeutral;
extern lv_obj_t * ui_ServiceValueSBStNeutralL;
extern lv_obj_t * ui_ServiceValueSBStNeutralR;
extern lv_obj_t * ui_ServiceSBStTurnGear;
extern lv_obj_t * ui_ServiceValueSBStTurnGearL;
extern lv_obj_t * ui_ServiceValueSBStTurnGearR;
extern lv_obj_t * ui_ServiceSBSpeedReqIdle;
extern lv_obj_t * ui_ServiceValueSBSpeedReqIdleL;
extern lv_obj_t * ui_ServiceValueSBSpeedReqIdle;
extern lv_obj_t * ui_ServiceStatistics;
extern lv_obj_t * ui_BotLineStatistics;
extern lv_obj_t * ui_ServiceNumSuccStarts;
extern lv_obj_t * ui_ServiceValueNumSuccStarts;
extern lv_obj_t * ui_ServiceNumUnscStarts;
extern lv_obj_t * ui_ServiceValueNumUnscStarts;
extern lv_obj_t * ui_ServiceStatisticsDayCons;
extern lv_obj_t * ui_ServiceValueDayCons;
extern lv_obj_t * ui_ServiceStatisticsTotFuelUsed;
extern lv_obj_t * ui_ServiceValueTotFuelUsed;
extern lv_obj_t * ui_ServiceStatisticsServiceTime;
extern lv_obj_t * ui_ServiceValueServiceTime;
extern lv_obj_t * ui_ServiceStatisticsRunHours;
extern lv_obj_t * ui_ServiceValueRunHours;
extern lv_obj_t * ui_ServiceBatteriesBox;
extern lv_obj_t * ui_ServiceBatteries;
extern lv_obj_t * ui_BotLineBatteriesBox;
extern lv_obj_t * ui_VoltagesBox;
extern lv_obj_t * ui_ServiceBatteryVoltages;
extern lv_obj_t * ui_ServiceBatteriesBar;
extern lv_obj_t * ui_ServiceValueBatteryVolt;
extern lv_obj_t * ui_ServiceUnitBatteryVolt;
extern lv_obj_t * ui_ServiceBatteryVolt;
extern lv_obj_t * ui_BatteriesLine100;
extern lv_obj_t * ui_ServiceUnitBatteryVoltBar100;
extern lv_obj_t * ui_BatteriesLine90;
extern lv_obj_t * ui_ServiceUnitBatteryVoltBar90;
extern lv_obj_t * ui_BatteriesLine80;
extern lv_obj_t * ui_ServiceUnitBatteryVoltBar80;
extern lv_obj_t * ui_BatteriesLine70;
extern lv_obj_t * ui_ServiceUnitBatteryVoltBar70;
extern lv_obj_t * ui_BatteriesLine60;
extern lv_obj_t * ui_ServiceUnitBatteryVoltBar60;
extern lv_obj_t * ui_BatteriesLine50;
extern lv_obj_t * ui_ServiceUnitBatteryVoltBar50;
extern lv_obj_t * ui_BatteriesLine40;
extern lv_obj_t * ui_ServiceUnitBatteryVoltBar40;
extern lv_obj_t * ui_BatteriesLine30;
extern lv_obj_t * ui_ServiceUnitBatteryVoltBar30;
extern lv_obj_t * ui_BatteriesLine20;
extern lv_obj_t * ui_ServiceUnitBatteryVoltBar20;
extern lv_obj_t * ui_BatteriesLine10;
extern lv_obj_t * ui_ServiceUnitBatteryVoltBar10;
extern lv_obj_t * ui_BatteriesLine0;
extern lv_obj_t * ui_ServiceUnitBatteryVoltBar0;
void ui_event_IncrementBar(lv_event_t * e);
extern lv_obj_t * ui_IncrementBar;
void ui_event_DecrementBar(lv_event_t * e);
extern lv_obj_t * ui_DecrementBar;
extern lv_obj_t * ui____initial_actions0;




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
