// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: P_1

#include "ui.h"

void SetBrightness(lv_event_t * e)
{
	lv_obj_t * slider = lv_event_get_target(e);
	BrightnessLevel = (uint8_t)lv_slider_get_value(slider);
	ChangeBrightnessFlag = true;
}

void SetBarValue(lv_event_t * e)
{
	lv_obj_t * bar = lv_event_get_target(e);
	BarValue = (uint8_t)lv_slider_get_value(bar);
	ChangeBarFlag = true;
}